### ISSUE TITLE
Add support for Playstation 1 games

### ISSUE THREAD

**Issue by XeresRazor** [jasarien/Provenance#58] opened 2015-03-24 15:43 UTC
Add support for Playstation 1 titles to Provenance.

**Comment by XeresRazor** [comment] 2015-03-24 15:43
I've started work on this using the PSXReARMed codebase.

**Comment by jasarien** [comment] 2015-03-24 15:47
Did you not fork and implement Mednafen?

**Comment by XeresRazor** [comment] 2015-03-24 15:48
I did, but I could never get performance to a point where it was playable, even on an A8 device.

**Comment by jasarien** [comment] 2015-03-24 15:51
Fair enough. I think the main barrier to a PSX core at the moment is the way Provenance currently handles ROM importing. CD based games require the cue sheet as well as the .bin or .img file, and right now .bins are assumed to be mega drive roms. It needs refactoring and some kind of user interface for a user to inform which system a CD is intended for (else there's no way to for the code to know).

**Comment by XeresRazor** [comment] 2015-03-24 15:55
I was thinking of modifying the search system to scan for cue's first, and then move PS1 games into a subdirectory in documents. Alternatively I think PSXReARMed supports the PSX2PSP eboot.pbp format, which can nicely wrap multiple discs in one package. If it does, I may just wire it up to only support that format.

**Comment by jasarien** [comment] 2015-03-24 16:00
The eboot thing sounds useful. In terms of the cue sheet thing, I think a more generalised approach will be needed in case other systems that use CDs are implement (eg, the Sega MegaCD which is already implemented, but just has no way of cleanly importing the CDs).

I'd like to refactor the entire game library/rom importer at some point anyway, it's in dire need of it :P

**Comment by iMartinKiss** [comment] 2015-09-19 14:03
Supporting PlayStation would be amazing.

**Comment by apexad** [comment] 2015-10-10 06:19
Any progress on this? I see that XerasRazor seems to have PSX working but it's based on a pretty old version of Provenance. Any chance in pulling that code over?

**Comment by jasarien** [comment] 2015-10-10 08:17
As XeresRazor says in a comment above:

> I did, but I could never get performance to a point where it was playable, even on an A8 device.

So no. There was some investigation into using a different emulation core (possibly psx reARMed) but I don't know if any progress was made.

**Comment by apexad** [comment] 2015-10-11 02:27
Looks like XerasRazor has not updated it in a year though. The new iPhones are faster now, it would be really great if you could try brining that code ever and updating it and running it on new hardware to see how it does.

**Comment by XeresRazor** [comment] 2015-10-11 03:26
If I get a chance I'll dig the code up and see how it's doing on my 6+.

**Comment by apexad** [comment] 2015-10-11 21:25
XerasRazor, just curious what format do the playstation games need to be in?  I have some Clone CD rips (ccd, sub, img) that open fine on PCSX-Reloaded on Mac OS X, but don't open in the emulator. (I added img as an extension in systems.plist).  Do you know of any Mac OS X compatible tools that can covert these Clone CD rips into bin/cue or iso files?

**Comment by brianmcdoogle** [comment] 2015-11-06 19:57
I hope this happens one day. It's my most wanted feature. Maybe the new 6S and 6S Plus have enough power in them to run things better.

**Comment by crxdelsol** [comment] 2015-11-06 20:03
+1

Would love to play classic PS1 games on the Apple TV.
(Same voor N64 and NGC. However I thing NGC is to hard to emulate on the Apple TV hardware)

**Comment by wahkiz** [comment] 2015-11-18 02:36
+1, playing psx games would be a dream on the new ATV. Feel like revisiting the times when I would play Crash Bandicoot from morning to night.

**Comment by bronnel** [comment] 2015-11-20 23:04
Yeas this is probably the most wanted feature, adding psx support with pcsx rearmed

**Comment by wahkiz** [comment] 2015-11-25 07:24
I noticed there is a fork for PSX in the graph, anybody can enlighten us on the situation of PSX support currently? I tried compiling but it was giving errors.

**Comment by jasarien** [comment] 2015-11-25 07:34
@wahkiz read the comments above yours. This has already been discussed.

**Comment by apexad** [comment] 2015-11-26 05:04
By the way, it seems to me by testing via RetroArch that the PSX Mednafen core is plenty fast enough on a 6s Plus. I am trying to see what I can do to update it and make a pull request, but it's a bit tough since it is on such an old fork.

**Comment by Mkaay83** [comment] 2015-12-05 23:57
Hey Guys!!! I appreciate your work!!! And Love to use Provenance on my iPhone and  TV4. I really enjoy to revive my childhood by playing classic SNES Games. I'm no coder Or programmer.. So i really don't know how much work you have to put into this. But i love it!! Even my girlfriend uses it to play Super Mario World 24/7 and she Is 28... ;)
So my questuion is... Btw it Is her question: will it be possible to Play Mario Kart from the Nintendo 64 someday?! It would be awesome!! So... Can you guys do that?! Greetz from Germany ;)

**Comment by jasarien** [comment] 2015-12-06 00:02
@Mkaay83 this is a ticket discussing PSX support. There is another ticket for N64: #17

**Comment by Mkaay83** [comment] 2015-12-06 00:20
THX man 😏

**Comment by outphase** [comment] 2015-12-31 04:16
Is there anything in OpenEmu's codebase that would help? OpenEmu recently added N64 and PS1 support.

**Comment by apexad** [comment] 2016-01-01 22:41
Between OpenEmu and RetroArch, the code is out there, but it will still take a considerable effort to port a PS1, N64, or any other video game core to Provenance. Especially in the case of PS1, since there will have to be somewhat of a refactor to allow multiple systems to have iso/bun/cue files (since currently MegaCD uses them).

**Comment by GutlessGnat** [comment] 2016-01-12 00:44
Pcsxrearmed doesn't work on non jailbroken devices in retroarch they use an interpreter core to get it to run. But then some games won't run on the interpreter.

The retroarch interface is clunky and hard to navigate. A standalone psx emulator like ppsspp would be ideal. Implementing it into a multi emulator would be difficult if you ask me unless you could make it run eboot files. Even ppsspp won't run those though.

**Comment by RedLucas** [comment] 2016-02-22 18:19
Forgive me if this is just non-sense, but could a potential solution to the multiple system having the same iso/bin/cue files be to change the file extensions to custom ones, then have the system still treat them as their original ones? Or something like game.psx.iso maybe.

**Comment by pmp174** [comment] 2016-02-23 00:41
@redlucas I think that would be too complicated . I think it would just be easier for the app to try and run each iso in a emulator core until it finds the correct one . ( trial and error)

**Comment by tonycoco** [comment] 2016-07-14 21:15
What about just using a folder structure?

**Comment by shruglins** [comment] 2016-08-30 18:22
Hi @jasarien , I guess this is still an ongoing petition as the issue hasn't been closed. I have done the porting of the psx emulator from the Mednafen emulator, just picked the one from OpenEmu and started changing stuff until it worked (basically I created a lib target for tvOS starting from the existing one in OpenEmu source code). 

There's still a lot of work to do, controller input still is not working, and some tricks have to be done to launch a game correctly (create some config files manually that Mednafen needs), also probably right now with the changes I did I broke compatibility with SegaCD (cue rom extension)... I did it quick and dirty because i just wanted to know how much time would it take to just launch a game and see the performance on the apple tv (which is good, psx emulation only takes 70% of the apple tv cpu).

So, if anybody is interested, I could upload a patch containing the diff changes I did. I don't know if you would like me to keep working on it and fix the stuff that's still broken, the truth is I don't have much free time to spend on this, so if you want to keep the code and do whatever you want feel free.

Cheers!

**Comment by apexad** [comment] 2016-09-08 00:30
You should definitely create a fork and push your changes to github.

**Comment by msikma** [comment] 2016-10-18 18:57
> @pmp174 "I think it would just be easier for the app to try and run each iso in a emulator core until it finds the correct one . ( trial and error)"

OpenEmu is able to ascertain which system an image is for by looking inside for a magic string.

Still...it is kind of a drag to have .cue, etc. files, and there's a second problem: multi-disc games. I still think it would be easier if we'd put all files into a directory, and then name that directory "GAMENAME.psxapp" or something like that. It's yet another non-standard implementation, but it would probably be better in the long run.

**Comment by msikma** [comment] 2016-10-18 18:57
@shruglins: I'd be interested in having a look at this. Would you be interested in putting the code on Github, or sending a patch?

**Comment by danielphillips** [comment] 2016-12-15 16:45
Is there anything available to have a look at?

**Comment by jasarien** [comment] 2016-12-15 16:46
Nothing that works

**Comment by shruglins** [comment] 2016-12-18 19:16
Hi,

as I'm a little lazy, I just created a patch that you can download from here: https://file.io/tLmQne

It's 29MB, the reason of the size I guess that comes from adding the whole mednafen library to Provenance (which is how psx emulation is implemented in OpenEmu).

As you will see in the patch there are still some hardcoded paths which need to be changed if you want to make it work on any machine.

Other things you need to know:

- I moved the cue files that were linked to Sega CD to be linked with PSX
- If you want to upload a game I just did it compatible with bin+cue format. You just have to put the cue file for Provenance to recognize it and put it in the library. After that you'll need to manually copy the bin files into the same path, you can do this easily with the built-in webserver.
- Also after you copy the bin and cue files, mednafen will crash because it needs different files like: psx BIOS, memory card files, mednafen config file... You can easily track all the files and paths were you need to put these files if you run Provenance through XCode as mednafen will tell you all these through the console.
- Control pad config is hardcoded, I played a lot to ridge racer and vagrant story with the nimbus steelseries so I configured taking into account it doesn't have select and start buttons.
- The screen resolution is hardcoded with an aspect ratio between 4:3 and 16:9, I did this because I don't like to stretch too much the image, also, there are some missing vertical lines, this is a bug and I couldn't figure out why is happening.
- Last thing: I don't know why but when psx emulation starts, it runs with "slow" emulation speed, you have to change it to "normal" speed.

**Comment by jasarien** [comment] 2016-12-18 19:21
@shruglins The link doesn't work: `{"success":false,"error":404,"message":"Not Found"}`

**Comment by shruglins** [comment] 2016-12-18 19:51
sorry, get it from here: https://github.com/shruglins/test

**Comment by msikma** [comment] 2016-12-18 20:52
What state of the repository does the patch apply to? I couldn't successfully apply it.

**Comment by jasarien** [comment] 2016-12-18 21:54
Same. I'd really prefer it if you'd fork the repo, apply your patch, then create a pull request. It'd make things 100 times easier.

**Comment by shruglins** [comment] 2016-12-19 19:23
I started working from:
`commit f7b9620154af7a2535a64435bd5f46fbe85defb8
Merge: 5eaf45c 67d9178
Author: James Addyman <addyman@me.com>
Date:   Fri Aug 5 08:47:56 2016 +0100

    Merge pull request #380 from kcm/saves-typo
    
    Small typo in saves instructions
`

**Comment by msikma** [comment] 2016-12-20 12:15
I still got an error while applying the patch, for some reason. I'm not entirely sure why since the patch looks fine. It was easy enough to fix, though.

Here's a fork with the patch applied. I haven't tried it yet, since I don't have the time at the moment.

https://github.com/msikma/Provenance/tree/psx-mednafen

**Comment by JoeMatt** [comment] 2016-12-20 14:05
I've also been working on this patch. It's been discussed in the slack channel but I didn't want to post it here until it was working.

This branch is up to date with master and has been converted to to a dynamic framework as the new method for building cores.

https://github.com/JoeMatt/Provenance/tree/mednafen

I'm wondering if this was ever tested on device since the included static libraries that are requirements, libsnd etc.., are x86 only binaries. 

I wouldn't get your hopes up on this one though. The ARM code isn't ARM64 so it has to default to the C methods. Also any dynamic recompilation / JIT won't work without jailbreak and Provnence doesn't aim to target jailbreaks. It's going to be too slow for PSX in all likelihood.

That being said, I had been planning on incorporating Mednafen for some time because it additionally supports other systems such as NeoGeo, Atari Lynx, TGfx16, Virtual Boy etc. This patch wasn't setup to support those systems but I'm assuming it can be done. Or at least, I'm willing to spend some time on it. These aren't exactly the most exciting systems to add but hell why not.

**Comment by shruglins** [comment] 2016-12-20 15:10
@JoeMatt I wouldn't say this works if I didn't test it in an actual device (an apple tv 4th gen).

I didn't mind compiling it on arm64 since armv7 runs perfectly smooth (at least in an apple tv 4th gen as I said before). I've been playing a lot to Ridge Racer, Pro Evolution Soccer and Vagrant Story and all of them run perfectly fine.

As you say, mednafen will be able to bring more systems to Provenance, I just wanted to play some time around with it and try to make psx work, of course you'll need to do some more work to do things in a more generic way, but it is easy to do now that you have mednafen implemented.

**Comment by JoeMatt** [comment] 2016-12-20 15:32
That's good to know. I'll continue work on getting it to work on current head.

**Comment by JoeMatt** [comment] 2016-12-21 03:12
OK, I figured it out. Core is running full speed on ATV. I overlooked where @shruglins mentioned the core speed keeps getting reset to Slow. Additionally had to fix some other issues with dynamic linking but all good now.

You can try my branch by checking out 
https://github.com/JoeMatt/Provenance/tree/mednafen

**Setup** 
- Put BIOS files in 'BIOS/com.provenance.psx'. You'll need to create this folder using the web import interface.
- For some reason it looks for a bios that's not included in a lot of BIOS packs. scph_7001.bin can be copy/renamed to 'scph5501.bin'
- BIN/CUE pairs will need to be zipped together. The importer doesn't quite work too well with CD images. They will end up in the 'conflict' folder. Just moved them to 'com.provenance.psx' or directly upload them there and then from settings choose 'refresh game library'. Now you should see your game under PSX.
- Run the game. Go to the menu and then game speed. Change to normal. This has to be done on every run until I figure out why it keeps resetting.

I would consider this very experimental at this point. It will probably effect the rendering of other cores due to some hard coded OpenGL changes that need to be changed to be core specific still.
You can install 2 versions of Provenance by choosing a new Bundle Identifier in the General settings of the build target in Xcode. Don't forget to change the TopShelf bundle id to match.

----
Since it's nearly XMAS I'll most likely fix the remaining issues and made a PR based on.
Then I'll continue to add in the additional systems that Mednafen supports that Provenance doesn't. (Atari Lynx, PC-FX, TurboGrafix 16/CD, Virtual Boy, Wonderswan.) Yeah, nothing too amazing but it would promote Provenance perhaps to show a growing list of systems both common and non.

It supports NeoGeo but for some reason OpenEMU used NoePop for that system, but I'll look into that too since there was already a request for it.

There's also a slightly updated version of Mednafen. Maybe it's worth looking into as it mentions some PSX tweaks for ARM, though if it's ARM assembly then it's most likely not ARM64 and not going to add any benefit since for some reason it appears you can't mix ARM7 assembly in an ARM64 build (though the CPU still supports those instructions. Maybe this is a technical limitation or just Xcode being Xcode.)

**Comment by appletv4** [comment] 2016-12-22 05:07
@JoeMatt I couldn't get psx working the app kept crashing when I try to open a game 

Here's what I did 

From your github link I put it in Xcode and choose mednafen (was I suppose to select master?)

I created the bios folder and second folder inside bios , I put the 3 bios bin files in there 

I have a couple of psx games both in bin/cue and .IMG 

i put the bin/cue game in to a zip together , i wasn't sure if I should put them in roms folder or .com.provenance .psx folder ?

I put them of both just to be sure , neither appears on the library , I then tried to put the bin/cue game without zip in psx folder but that didn't work either 


The one game that did show up was an .IMG  and the app crashes when I try to open the game

**Comment by JoeMatt** [comment] 2016-12-22 05:16
Yes, use the mednafen branch.

As far as the games, If they're zipped, they go in ROMS folder. I actually haven't tested if the conflict manager works though and you'll most likely need to run that after import.

Instead in the meantime, you can just put the bin(s) and cue together (not zipped) in the com.provenance.psx folder and do a rescan. It's likely crashing because the .img isn't known and there's an assert() there that will later be replaced with an error message.

----
Since I'm posting anyway, I'll update.

1. Wonder Swan, Virtual Boy and Atari Lynx have been added. 
2. Fixed an issue with crashing on return to library.

Outstanding:
1. Cores starting in Slow mode
2. Button mappings are lined up but wrong with MFi in some cases
3. On screen controls haven't even been done on anything
4. Rendering dimensions of new systems is off due to OpenGL changes in PSX patch
5. Add NEC PC-* systems

**Comment by leoderbois** [comment] 2016-12-25 19:21
I tried it today with few games, THPS, Crash Bandicoot, Tekken 3, Ridge Racer, Ape Escape (fail), and that's works great, I passed a nice Christmas with my bro with this ^^ But it look like Joystick not works on Nimbus controller, it reproduce  the cross direction action. The only games I know which needs separate command from Joystick is Ape Escape, so perhaps it could be a nice "test game" for you.

**Comment by brianmcdoogle** [comment] 2017-01-08 22:22
So, I tried this today and it works really great. Couple of things I encountered that I thought I'd share for anyone trying things.

1: After importing a zip of bin/cue files, it crashes. Load it back up, and it will prompt the conflict manager. Select the PSX option, and it might crash again, or might not. Load it up again and the game will be in the library and work. I only tried this with one game, and it was a zipped file in iCloud that I copied into Provenance using the share sheet "Open in App...". Maybe this issue isn't there when you use the server or file browser on a computer.

2: Fast speed doesn't work. It gets wonky and goes super slow. Games do start in slow motion, but putting them in Normal after launch works well enough. I do experience some slowdown at times that I don't in RetroArch.

3: Controller mapping seems fine. You can use the analogue sticks on an MFI controller to simulate the d-pad if you rather use sticks. I'm not sure, but I think start/select are mapped to triggers. I also don't know how things work in games that use analogue controls like Ape Escape. 

4: I haven't played with things enough, but I'm not sure how switching between discs will work for some games (like Final Fantasy VII). If you use PCSXR on a computer, you can use your old MCR saves so long as you rename them....

4a: I don't know if you can import mcr files. I doubt it. That would mean you would need to use a computer to copy file names and get things working on a computer first.

5: You can delete and add from other apps, like iCloud or Dropbox or wherever. This means you can download on the go and delete if you fill up storage. This can't be done with RetroArch on iOS to the best of my understanding.

6: When I first tried to get it working, it wasn't finding the Mednafen framework. If this happens to anyone else attempting this, go to the build settings and make sure it is added in frameworks. A wrong version in the derived data was getting added by mistake and causing lots of errors.

I'm really happy with how things work so far! It doesn't run as smooth as pcsx rearmed interpreter in RetroArch for me, and it doesn't look as good (things are more pixelated in Provenance with Mednafen). But, this is a really cool thing. 

Great job! Now, once a cheat interface gets up and running, and maybe a dark interface gets added, I think I'll probably be done with RetroArch.

**Comment by somejonus** [comment] 2017-01-26 22:20
Great work on this, thank you guys so much!

I have an idea regarding the button mapping to an MFi controller. Maybe it could work without occupying the R2 and L2 triggers if the buttons are soft. So when you want to press either select or start you first press the menu button and then choose the button you want by joystick or have them mapped to the 2 triggers inside menu. For example: hit Menu then R2 and voila – you are back ingame and the start-button has been pressed.

**Comment by brianmcdoogle** [comment] 2017-01-29 07:21
So, I'm trying to resolve the resolution issue where anything but PSX games are borked. shruglins or JoeMatt, can you point me where the resolution settings are being overwritten to force the new resolutions? I want to see how things look with the original settings since they work perfectly with everything but PSX games, and I want to see how bad it is when running PSX games.

**Comment by JoeMatt** [comment] 2017-02-03 17:20
In 

> - (void)glkView:(GLKView *)view drawInRect:(CGRect)rect
> PVGLViewController.m 

Really easy to change, wasn't really being held back by this bug. I'm still looking at why the speed values get messed up on init.

**Comment by mathewrennie** [comment] 2017-02-07 12:43
@JoeMatt The speed values are being messed up by the Master Clock references within OpenEmu coding.  Using the branch from @msikma I removed the Master Clock coding and the PSX games ran at full speed on load. Your coding is a bit more complicated to go through as you've added further support in the MednafenGameCore.mm file for other emulators.  

Hopefully though it will help you to go over your code and resolve the issue.

**Comment by mathewrennie** [comment] 2017-02-08 18:42
@JoeMatt It does seem to be the Master Clock is the issue, I've went through your coding and removed references and PSX games load at normal speed. I'm now working on tidying up some loose coding for aspect ratio.  Once completed I will upload code to GitHub for others to mess around with. Regards.

**Comment by mathewrennie** [comment] 2017-02-08 19:48
Ok, so I've uploaded my version to GitHub for those to mess around with, I've modified the upload server to help newbies understand the way's to upload PSX roms. 

https://github.com/mathewrennie/Provenance-galnet-mednafen

Fixes I've Made Include:

1. Crash when opening up another PSX game after closing another one down.
2. Speed Load, Games now load in at normal speed.
3. Fixed issue with aspect ratio.

I've noted tested any of the other emulators which @JoeMatt had added to his repo, so please don't shout at me if these aren't running correctly.

Let me know if you have any issues, and would be happy to help others in coding should they have issues.  Let's make Provenance one of the best emulators around from the Apple TV 4.

**Comment by brianmcdoogle** [comment] 2017-02-08 21:37
@mathewrennie 
Hi there. I tried your version but I'm running into strange issues. I'll note that I'm not using it on an Apple TV 4, but a 9.7 iPad Pro. 

1. I haven't had any crashes when switching between PSX games, so that seems to be working for me. 
2. Game speed still doesn't work correctly for me. In JoeMatt's version, once I switched to normal after loading a PSX game, it would run fine. Your version doesn't run smooth, and I get a lot of stuttering in video and sound effects; everything progressively gets slower as time goes on and the sound stuttering does not improve even when switching between game speeds. "Normal" never runs at normal speed, always slow and stuttering.
3. The aspect ratio has been fixed for all non-PSX games now, but PSX games are shifted to the right and not centered. I wonder if this is because the iPad's screen is 4:3 while the TV is 16:9? Basically, it's the inverse of the problem I mentioned earlier in JoeMatt's version. His shifted every thing to the left except PSX games which were centered while yours shifts everything to the right, making every thing centered except PSX games which are now cut off on the right.

Are the other emulators, like NES/SNES/SegaCD, all assuming a 4:3 display and that's why they display correctly while Madnafen assumes a 16:9 and so it works correctly for Apple TV but not iPads? 

Hope all of that makes sense. I can post screenshots of the resolution issues on an iPad if it would help. The bizarre thing is the game speed is worse now for me, as changing the speed doesn't get a normal speed and it is now stuttering on every PSX game I've tried. 

Oh, and one last thing that applies to both yours and JoeMatt's version: my MFI controller always switches to player 2 after starting a PSX game. It doesn't cause any problems, but I've noticed this is a consistent thing and don't know how it would affect 2 player games or something like Metal Gear Solid.

**Comment by JoeMatt** [comment] 2017-02-09 00:41
@mathewrennie If did a GitHub fork instead of an upload as a new project, I could actully see your diffs. As of right now I don't know what the changes are. If you tell me what the changes are to prevent crash on reload, I'll add them into my branch.

I have a fix for the runspeed and it's nothing that's mentioned  here. I has to due with mednafenCoreTiming variable changing on each frame around 60 frames, but sometimes more, sometimes less. That variable is used to set the framerate, which is used to calculate gameInterval, which is used to determine if the game loop thread should sleep. Either it's a race condition on startup when the value is read, or it's something else related. The simple fix seems to be to just hardcode the frame frame to 60. I'm testing if that effects the other systems in Mednafen and then push that change.

**Comment by JoeMatt** [comment] 2017-02-09 01:57
Branch is updated. I fixed both the stutter issue and the crash on reload. 

That just leaves the aspect ratio stuff. This has to be changed system by system in the core so it's not as easy as an if/mednafen fix. I'll try to take a look sooner than later. It's not difficult, it just takes time to implement it right.

**Comment by brianmcdoogle** [comment] 2017-02-09 05:07
I did a restore and was able to get things working properly again. Don't know why I was having so many issues this time, but the restore from backup after deleting the app worked.

Speed does work fine now at start. Yeah, the crash on reload is still there but that's minor. Things are looking pretty good.

It makes sense that a if/mednafen fix would probably not be the greatest, but I figured I would give it a shot until someone else did a proper fix; this now works fine for me (except the boot of PSX is still offset, but once you get in the game it looks fine). I changed things in 
(void)glkView:(GLKView *)view drawInRect:(CGRect)rect
PVGLViewController.m


	NSString* checkCore = self.emulatorCore.systemIdentifier;
   	if ([checkCore isEqualToString:@"com.provenance.psx"]) {
	    vertices[0] = GLKVector3Make(-1.2, -1.0,  1.0); // Left  bottom
	    vertices[1] = GLKVector3Make( 1.0, -1.0,  1.0); // Right bottom
	    vertices[2] = GLKVector3Make( 1.0,  1.0,  1.0); // Right top
	    vertices[3] = GLKVector3Make(-1.2,  1.0,  1.0); // Left  top

	    textureCoordinates[0] = GLKVector2Make(0.0f, texHeight); // Left bottom
	    textureCoordinates[1] = GLKVector2Make(texWidth*1.1f, texHeight); // Right bottom
	    textureCoordinates[2] = GLKVector2Make(texWidth*1.1f, 0.0f); // Right top
	    textureCoordinates[3] = GLKVector2Make(0.0f, 0.0f); // Left top

	}
	else {
	    vertices[0] = GLKVector3Make(-1.0, -1.0,  1.0); // Left  bottom front
	    vertices[1] = GLKVector3Make( 1.0, -1.0,  1.0); // Right bottom front
	    vertices[2] = GLKVector3Make( 1.0,  1.0,  1.0); // Right top    front
	    vertices[3] = GLKVector3Make(-1.0,  1.0,  1.0); // Left  top    front
	    vertices[4] = GLKVector3Make(-1.0, -1.0, -1.0); // Left  bottom back
	    vertices[5] = GLKVector3Make( 1.0, -1.0, -1.0); // Right bottom back
	    vertices[6] = GLKVector3Make( 1.0,  1.0, -1.0); // Right top    back
	    vertices[7] = GLKVector3Make(-1.0,  1.0, -1.0); // Left  top    back
			
	    //GALNET GRAPHICS FIX END
			
	    textureCoordinates[0] = GLKVector2Make(0.0f, texHeight); // Left bottom
	    textureCoordinates[1] = GLKVector2Make(texWidth, texHeight); // Right bottom
	    textureCoordinates[2] = GLKVector2Make(texWidth, 0.0f); // Right top
	    textureCoordinates[3] = GLKVector2Make(0.0f, 0.0f); // Left top	
	}

**Comment by mathewrennie** [comment] 2017-02-09 13:38
@JoeMatt Sorry that's my bad.  I'm busy today so can't really do much, but I will delete the Repo and from now on make sure I'm working on your fork to help things along.  I uploaded directly from my Mac without thinking.   Cheers, Mat.

**Comment by mathewrennie** [comment] 2017-02-09 14:07
@brianmcdoogle you are right about the differences on iPad and Apple TV..  I created that code based only on what I was seeing via the AppleTV.  I do have an iPad Pro so will use this to cross examine things. @JoeMatt for reference are your testing your coding on an iPad or AppleTV as it could be both systems are conflicting.

**Comment by mathewrennie** [comment] 2017-02-09 14:25
@JoeMatt just quickly to stop the crashing on reload here is the patch:

To stop crashing when reloading PSX Game:

In settings.cpp change:

 if(FindSetting(setting->name, false, true) != NULL)
  {
   printf("Duplicate setting name %s\n", setting->name);
   abort();
  }

To:

 if(FindSetting(setting->name, false, true) != NULL)
  {
   printf("Duplicate setting name %s\n", setting->name);
  }

The duplication doesn't seem to effect things.

**Comment by mathewrennie** [comment] 2017-02-09 19:03
@brianmcdoogle I've uploaded a new build to GitHub, it includes your If Else statement for the time being.  I've also sorted game speed issues for both iPad and Apple TV.   Not had any issues so far when running.  Also in relation to 2 player and controller this isn't an issue as it's simply fixing a controller type to both player 1 and 2. As such player 2 can use another controller within settings.

@JoeMatt I've not forked this build yet as am still not sure if your testing just on iPad/iPhone or indeed both iPad/iPhone and Apple TV?

**Comment by rbissoli** [comment] 2017-02-10 14:53
Hi guys! You all have done an incredible work porting madnafen psx to provenance.
 
I've compiled using xcode 8.2 for iOS 10.2.1 and it actually works fine. I have a logitech mfi controller and it also works properly. There is a problem when not using a mfi controller. Everytime I touch some button on the screen the emulator crashes and I have to restart everything again. I noticed that GBA/Genesis/SNES emulation the touch buttons work properly and I can play without any issues. Is that a button mapping problem ? 

Thank you again :D

**Comment by JoeMatt** [comment] 2017-02-10 22:09
@mathewrennie  it actually crashes on the math test and the settings test. What's happening is that these static variables aren't going away or being reset when the core is killed. So, it might be possible to just ignore them for now by over-stepping those calls, but it's probably a really bad idea to leave junk laying around between runs. Also this would probably effect running games from different systems back to back because of the duplicated settings.

I'm testing mostly on apple TV, though I once in a while do a build for iOS.

A better test than looking for the core "com.provenance.psx" would for the core itself to return a Bool value that is defaulted in the super class as NO. And then MednafenCore could overload it to return YES depending on the system. The GL view having to have working knowledge of the cores and doing the switching itself is a poor separation of duties.

**Comment by JoeMatt** [comment] 2017-02-10 22:10
I have free time this weekend, I'll try to bang this out.

**Comment by rbissoli** [comment] 2017-02-13 15:39
I would be great Joe. My mfi controller is pretty basic, It is similar to a SNES controller and doesn't have analogic sticks or L2, R2 buttons. I was wondering if would be possible to have a option to leave the buttons on screen even if the mfi controller is connected or if I could customize which buttons I would like to leave on screen when using the mfi controller. It would be really awesome and break some controllers limitations ! Thanks again guys!

**Comment by JoeMatt** [comment] 2017-02-13 21:35
@rbissoli  Customizing controls and/or leaving them on screen would need to be a Provenance feature and wouldn't pertain to this ticket. I think there's already a ticket for customizing controls #306 #38 #37

**Comment by rbissoli** [comment] 2017-02-15 17:47
thanks @JoeMatt , I've posted in the referenced ticket.

**Comment by BobLoblaw74** [comment] 2017-03-26 03:20
Great work @JoeMatt on this, I was able to import 2 PSX games and run them on my Apple TV 4 and they seem to be working fine! The only issue is... I am using a SteelSeries Nimbus controller, and for some reason none of the button works, which is surprising since the same controller works for all the other consoles in Provenance. 
Does anybody have any idea how to fix this issue? Thanks!

**Comment by JoeMatt** [comment] 2017-03-27 16:29
@BobLoblaw74 Make sure you have the latest version of my branch. I updated it ~2 ago or so. I'm still working on controllers though my memory says PSX was mapped. Make sure the Nimbus is set to controller 1 and working on other systems. Often for me my controller jumps to Player 2 if it goes to sleep for instance.
 I'm close to making an official pull request for this branch. Some things to touch up and test MFi controllers on all the cores thoroughly.

**Comment by BobLoblaw74** [comment] 2017-03-28 00:55
@JoeMatt I am on commit e0cd4d1 on the mednafen branch.(I cloned it last Saturday). Is there a newer version? I did make sure that Nimbus was on Controller 1, and I could not get it to work on PSX, but was able to use it on Genesis or SNES immediately after. Thanks for your help!

**Comment by JoeMatt** [comment] 2017-04-07 04:53
I just updated my branch with full MFi controller support. I tested every core and they seem to have logical button mappings. I used right paddle select, left start for console with those buttons. PSX has dual analog stick support as well.

Still have a bug where sometimes the system will start slow, change game speed to normal resolves this. I have a hack that fixes this most of the time but it's a hack and not perfect. Have to figure out the root cause still.

For some reason bin/cue conflicts show up for me on iOS, but not on tvOS. For tvOS when importing PSX or PCFX-CD games, manually move them to the proper system folders and rescan the library for now. Should make a separate bug ticket for the conflict UI on tvOS.

Not sure if this is a good point to make a pull request and live with the speed workaround or wait until I have that fixed. I might not have that much time coming up though. I have a huge backlog of other projects that are becoming more time sensitive.

**Comment by t4t5** [comment] 2017-04-07 06:35
@JoeMatt Thank you so much for your work on this!

**Comment by lolkthxbai** [comment] 2017-04-08 02:10
@JoeMatt truly fantastic work!

**Comment by BobLoblaw74** [comment] 2017-04-08 02:58
@JoeMatt thanks a lot, I am now able to use the D-pad and the main buttons on my Nimbus! Great job!

**Comment by fabd** [comment] 2017-04-16 11:40
This would be freaking amazing if possible. Although the titles I am eying on could be difficult to emulate, in particular the Wipeout series. **Wip3out** (3rd) has some kind of high resolution (double vertical lines) (or was it alternating lines mode). If those games don't run at full speed they're not really playable. **Rapid Racer** also uses the high res mode.

**Comment by JoeMatt** [comment] 2017-04-16 23:59
@fabd See #566

**Comment by appletv4** [comment] 2017-05-17 19:44
People looking for a second controller , amazon has the steelseries nimbus controller for $26 with code ON96RMRZ
As of 4pm 5/17
Amazon USA

**Comment by JoeMatt** [comment] 2017-05-17 22:08
Code seems to only work on the refurb version,
https://smile.amazon.com/gp/product/B07119SH6G/

**Comment by jgstroud** [comment] 2017-07-08 21:11
I checked out the Mednafen+Atari800+Poke branch, and it seems to be running well.  However, my Nimbus analog sticks aren't working.  The play station games think I don't have an analog controller connected.  I see commit 2740340 should have fixed this.  Any idea what might be going on?

**Comment by jgstroud** [comment] 2017-07-09 02:18
I was having trouble getting my analog sticks to work.  The emulator seemed to be stuck in "gamepad" mode.  I ended up modifying the DualShock::Power function to force analog=true at init.  This fixes my problem with the analog sticks, but I'm sure there is a better way to fix this.

**Comment by jgstroud** [comment] 2017-07-09 17:45
I'm not sure why others don't seem to be reporting the same problem I am having, but I added a way to toggle the controller between analog and digital mode (most games seem to work well with analog, but Crash required digital mode).  I was debating between 2 different methods of doing this: See commits on my fork: 50acca7c5d98293c4a95919faa80f672daa795a4
 and b480915345ae112b58ab2784982e3046f31c0987
The first avoids any changes to the mednafen code, but the other seems a bit cleaner to me.

**Comment by JoeMatt** [comment] 2017-07-10 06:53
I believe others have reported similar problems. The PSX emulator we use (mednafen) has support for analog and non analog versions of the original PSX controllers (even non released versions). The issue as i understand it is how to appropriately present the correct controller type based on rom because some complain about the old or the new depending on their heritage. There's a rom SKU mapping to multitap in MednafeGameCore.mm for controller functionality. Perhaps that's an insight to resolve this type of issue. I ripped it out of OpenEMU,so if it works in OpenEMU but not Prov then it's something we can maybe fix. If not...

**Comment by jgstroud** [comment] 2017-07-10 18:43
Yeah, I was hoping to set it based on the ROM, and this would ultimately be the best way to do it.  For now, I am using this AMCT button combination to switch the controller type and it works quite well.  My biggest gripe was that it default starts in gamepad mode, and probably 90% of the time you'll want analog mode.  So I changed the default.  My first attempt at patching, I also had to change the button combination from the default because it wanted Select, Start, and all 4 shoulder buttons to switch modes.  I changed it to just all 4 shoulder buttons.  Then I saw that the upstream mednafen code makes this button combination user selectable, so I merged that change and added the combination to the init code in MednafeGameCore.mm, which seemed like the cleanest way since it basically leaves the upstream code untouched.

**Comment by barlarb** [comment] 2017-11-26 01:02
Can somebody please upload a working .ipa? 
I would be so grateful!
I can't for the life of me get this to work, despite following the instructions to the letter multiple times.
I'm running Mac OS X 10.13 High Sierra, Xcode 9.1, iOS 10.3.3
Thank you in advance.

**Comment by barlarb** [comment] 2017-11-26 01:20
@JoeMatt 
Would this be possible?

**Comment by JoeMatt** [comment] 2017-12-17 05:03
Unfortunately uploading an IPA would be futile since it would only be an ad-hoc build for my registered devices. It would have to be resigned using tools or Xcode which one could argue would be non less difficult than just building ones self from source.

Most of this has been answered in #566, continue any PSX discussion there.

**Comment by JoeMatt** [comment] 2018-01-08 01:34
This is in main after Mednafen merge.

**Closed by JoeMatt** 2018-01-08 01:34 UTC
Labels: Emulator Core, Enhancement

**Comment by XxXStefannXxX** [comment] 2018-02-10 15:04
I know I am not in the right discussion room but i have a request to make, to all programmers working on Provenance. Would it be possible to make r2 and l2 buttons in the app? Some update or smth? I’m not an expert or anything, and don’t know how its made but it would be great to have all buttons that were on Ps1 controller. Thanks guys

**Comment by JoeMatt** [comment] 2018-02-10 17:33
@XxXStefannXxX Already an issue being tracked #644
