### ISSUE TITLE
2 Players 8BitDo Zero

### ISSUE THREAD

**Issue by loserkid520** [jasarien/Provenance#611] opened 2017-11-15 16:21 UTC
I tried connecting two 8bitdo zero controllers to Provenance but it’s responding in a way that it only uses one controller and not two. It’s responsive to both controllers, but whatever player one presses in either controller, player two’s character will only follow the commands given to player 1

**Comment by jasarien** [comment] 2017-12-19 23:28
This is because how iCade controllers work. I believe they have different mode settings. If both controllers are in the same mode, then they are sending the same key-press commands which provenance interprets for player one. 

In any case, I don’t think support exists in Provenance for multiple iCade controllers.

**Comment by jasarien** [comment] 2017-12-20 01:08
Duplicate of #523

**Closed by jasarien** 2017-12-20 01:08 UTC
