### ISSUE TITLE
Error on Building "ld: library not found for -lPVGBATV"

### ISSUE THREAD

**Issue by sean808080** [jasarien/Provenance#104] opened 2015-09-21 01:34 UTC
New install of Xcode 7.1 Beta, opening the workspace and no matter how many settings I try to finagle I can't get a build to complete successfully.  Tried with the new ATV connected as well as the Generic tvOS device device.  Any ideas are appreciated.

![screenshot](https://cloud.githubusercontent.com/assets/203494/9984095/653ad906-5fdf-11e5-897b-8f1164129ff1.png)

**Comment by kckd** [comment] 2015-09-21 01:36
It looks like you opened the project rather than the workspace. Try opening the workspace instead.

**Comment by sean808080** [comment] 2015-09-21 01:38
Pretty sure it's the workspace.  See this:

![screenshot](https://cloud.githubusercontent.com/assets/203494/9984119/faa7a7bc-5fdf-11e5-92b6-e4c52b532cd6.png)

**Comment by jpete24** [comment] 2015-09-21 01:40
You want to open the workspace file, not the .proj file when you open it from Finder.

You could also turn off ENABLE_BITCODE which you search from the "filter" search area on the top right.

**Comment by kckd** [comment] 2015-09-21 01:45
Maybe try changing the target device to the tvOS simulator (or the Apple TV itself if you have it). It built straight out of the box for me.

**Comment by sean808080** [comment] 2015-09-21 01:54
I was hopeful the bit code flag would do it.  No glory.  Still the same error despite trying device or simulator.  Spent an hour last night fussing with this and not sure where the issue is.

**Comment by jasarien** [comment] 2015-09-21 06:20
It might sound weird, but try moving the whole project directory to the desktop (or somewhere outside of that _TechLife folder). That underscore prefix could be interfering, maybe. 

If that doesn't solve it, I'm not sure. Are you using El Capitan?

**Comment by jasarien** [comment] 2015-09-21 16:22
Any update on this?

**Comment by imaurus** [comment] 2015-09-22 09:25
Just add the file Real.framework that you find inside the folder to Build Phases->Link Binary With Libraries.

**Comment by sean808080** [comment] 2015-09-22 15:16
@imaurus  the realm.framework is already there
@jasarien  Tried moving it to the home directory. same result.  it builds fine on another machine.  I'm good for now.  Haven't figured out the diff yet.

**Comment by jasarien** [comment] 2015-09-22 15:35
How interesting. Glad you can build on another machine. I'll close the issue for now. If you figure out the cause leave a comment here.

**Closed by jasarien** 2015-09-22 15:35 UTC

**Comment by tylerarnold** [comment] 2015-11-30 23:44
I am encountering this issue right now. "ld: library not found for -lPVGBATV", I am using Xcode "Version 7.2 beta (7C62b)"

**Comment by tylerarnold** [comment] 2015-11-30 23:55
I am opening it via the workspace and have fiddled around with the schemas to see if any change occurs with the linking. I suspect perhaps a sequencing issue or pathing issue -- perhaps lib PVGBATV is being put elsewhere.

**Comment by hstriepe** [comment] 2015-12-01 00:02
Problem confirmed - Xcode 7.1.1

**Comment by tylerarnold** [comment] 2015-12-01 17:48
while experimenting, I also found it fails similarly for other targets. I tried building for "Provenence" /iOS and I also get a linker error, but this time it is: "ld: library not found for -lPVSupport
clang: error: linker command failed with exit code 1 (use -v to see invocation)
"

**Comment by jasarien** [comment] 2015-12-01 20:16
Question, are you an Admin user on the Mac you're building on?

**Comment by hstriepe** [comment] 2015-12-01 20:17
I am.

**Comment by jasarien** [comment] 2015-12-01 20:19
So the only difference I can see is that the linker command Xcode is using is referencing a Build folder from inside the Provenance Project directory, which shouldn't be there. It should be inside the Derived Data folder under `~/Library/Developer/Xcode/DerivedData/` and I can't see a reason why it's not using Derived Data on your machines. Do you have custom Locations set up in Xcode Preferences?

**Comment by tylerarnold** [comment] 2015-12-01 20:34
I am admin on my machine, no custom locations, they are all set as "~/Library/Developer/Xcode/DerivedData/" ,etc.  However command line tool is set to 7.1.1.. I will investigate that.

**Comment by hstriepe** [comment] 2015-12-01 20:36
Ditto.

**Comment by tylerarnold** [comment] 2015-12-01 20:39
no difference changing the command line tool.hmm..  probably some related environment variable though.

**Comment by tylerarnold** [comment] 2015-12-01 20:47
I got it to build, I went and changed Derived Data's location to Custom > Relative to Derived Data.

**Comment by jasarien** [comment] 2015-12-01 20:49
But that doesn't make any sense and shouldn't be necessary. By default the built products should be placed inside a unique directory for that project within DerivedData...

**Comment by tylerarnold** [comment] 2015-12-01 20:50
yeah I am totally confused why that fixed it.

**Comment by tylerarnold** [comment] 2015-12-01 20:55
and I went and changed it back to the default location, did a clean, and rebuilt and... of course it compiles now. My hypothesis is there either something dirty in my environment or something 7.2 beta 4 does differently.

**Comment by hstriepe** [comment] 2015-12-01 20:56
Did not solve it here, but I will do a clean checkout next.

**Comment by azroach** [comment] 2016-02-28 06:18
you get this error when you open the project with the blue icon!  open the workspace with the white icon!

and you can't build it if you set bit code to "no" because its required to build on twos!

**Comment by Marvin91** [comment] 2016-06-09 21:42
brutal workaround:
copy libPVGB.a libPVGBA.a libPVGenesis.a libPVNES.a libPVSNES.a libPVSupport.a from "PV*/build/Release-iphoneos/" to "Provenance-master/build"

or try to use another account on the same computer
