### ISSUE TITLE
iOS - Crash when airplay mode is on 

### ISSUE THREAD

**Issue by okenjaev** [jasarien/Provenance#476] opened 2016-12-06 19:46 UTC
I have enabled the airplay mode and wanted to start a game but the app crashes.

After some research, I have realized that when Show FPS count is on in settings, the app crashes with airplay mode. 

I could fix it

**Comment by marcelvoss** [comment] 2016-12-24 11:50
Can't reproduce this. Could you maybe attach a crash log? cc: @jasarien

**Comment by sevdestruct** [comment] 2018-03-07 11:35
Gonna close this, as we have a fully functional tvOS app, and there is OpenEmu for Mac there is no reason to AirPlay the iOS app to anything when you can avoid that latency, which kind of renders the FPS test moot really, play without it across airplay and see for yoursrlf, then just go install the tvOS build to run narively.p and be done with it.

**Closed by sevdestruct** 2018-03-07 11:35 UTC
Labels: Can't Reproduce, Require More Info
