### ISSUE TITLE
Retain Custom Art on Library Refresh (as Default or as Option Toggle)

### ISSUE THREAD

**Issue by BaffleBlend** [jasarien/Provenance#730] opened 2018-03-08 01:35 UTC
Hello again. I use Provenance with a lot of unlicensed, homebrew, and hacked games which, for obvious reasons, aren't on the OpenVGDB database.

I don't mind adding the covers for these games manually (many of which have to be custom-made), but every so often, the image cache is cleared by another tweak or setting, forcing me to repeat the entire process.

Because of this, I'd like the option to permanently store the image cache somehow, as a safeguard against when this happens.

**Comment by JoeMatt** [comment] 2018-03-09 02:57
I think I need more info on what scenario is causing the image cache is even be cleared? That sounds more like the bug here. You can mass import though so you could keep a local folder of your custom artwork and copy it all in to the upload folder if you lost it somehow.

The image cache that stores artwork is based on the md5 of the filename, or the URL if it's a remote image, since the image cache is used for local and remotely imported files. For instance, it caches back box artwork which is downloaded on demand when browsing the more info view and its downloaded from an online site automatically if the database has the URL. I can't think off a good way to really back this up with the current architecture being changed. The PVGame instances in the database contain both the artwork url if it's in the OpenPV database, and an optional other url field if custom artwork is set, that points to a local file URL after it's moved into the image cache.

Only thing I can think of that would cause issues is if Apple TV does it's auto disc cleaning crap but that's a problem for everything including ROMs. The only fix for that would be to add off site backup / import which is kind of a ways away.

**Comment by BaffleBlend** [comment] 2018-03-09 03:06
@JoeMatt: what caused the clearing at least the first time was iCleaner. It did not ignore Providence despite my specifying it to.
As for the other times, I'm not sure, though I'm positive it was while installing some other tweak.

@sevdestruct: Thanks, I'm doing that.

**Comment by JoeMatt** [comment] 2018-03-09 03:15
@BaffleBlend Well if that's the case not sure how to fix that. If it clears our image saves, then it just is what it is, a bug in iCleaner. They are 'permanently' saved as we have it coded now.

**Comment by sevdestruct** [comment] 2018-03-09 03:26
@JoeMatt, actually there is an issue with persistence regaring the use of the Refresh Game Library action:

<img width="391" alt="icloud_photos" src="https://user-images.githubusercontent.com/3118097/37188733-84beb89c-2305-11e8-979a-96f9736de1d7.png">

…which will clear all custom art ROMs to blanks again (or matches if it succeeds on finding something I suppose. But I can confirm this, just tested it and lost all my custom art work in the app. I also tested custom art over ROMs that weren't blank or missing art, and confirm that they also get reset when this is used.

@BaffleBlend, did you happen to this?

Regardless it's something that needs fixing, (or there is a use case scenario where people want that to happen 1. in hopes of new artwork match on custom swaps, or 2. custom swaps that people want to reset back to original all in one swing (the more likely use case), and either above scenario is wanted then I propose a toggle below this button that says:

**Retain Custom Artwork** [On/Off]

**Comment by JoeMatt** [comment] 2018-03-09 03:32
'Refresh game library' would have to be re-written then. We would have to create a backup of the current PVGames before clearing, then when you do the new import, look at this backup data for custom data, or have 'Refresh Game Library' not do a clear but only a scan, or make it an option at least. Right now it does a DB flush which is why you're losing the references to custom artwork, and since the artwork is named by an MD5 of the file that was imported, it's basically impossible to figure out which image is the right one on re-import since there's no way to know what the originally used filename was without that data being pre-backed up.

**Comment by JoeMatt** [comment] 2018-03-09 03:37
Added #739. Closing this bug since that issue tracks the grander issue.

**Closed by JoeMatt** 2018-03-09 03:37 UTC
Labels: bug, enhancement
