### ISSUE TITLE
Build issue caused with Wonderswan dual D-Pad hack

### ISSUE THREAD

**Issue by Cepheidsong** [jasarien/Provenance#624] opened 2017-12-18 14:49 UTC
Hello

Trying latest build just put up, but xcode causes failure which seems to be in the Wonderswan dual D-Pad section.

the error is in dPadFrame.origin.y = dPadOriginY - size.height - bottomPadding;

where is an undeclared identifier.  I tried adding frame. and self. or other things just to see what would happen, or removing size., but gives error still.  So I removed "- size.height" entirely from the line and Provenance builds and runs, but I don't know if that's going to cause any wonderswan issues, so passing it along.

**Comment by jasarien** [comment] 2017-12-18 16:23
Just commiteed a fix for this. Can you pull the latest and see if the issue is solved.

**Comment by Cepheidsong** [comment] 2017-12-18 17:11
Build successful!  Runs OK.

**Closed** 2017-12-18 17:14 UTC
