### ISSUE TITLE
Add support for MAME

### ISSUE THREAD

**Issue by RECONX1** [jasarien/Provenance#185] opened 2015-11-07 00:01 UTC
Would love to see support added for MAME roms. One of my favorite arcade games to play back in the day was X-Men. I found the 4 and 6 player roms for it but since it's a MAME rom, I can't play it.

**Comment by jasarien** [comment] 2015-11-07 00:04
Duplicate of #152. **Please** read existing issues, *closed and open* before posting new ones, chances are high that someone has already posted it!

**Closed by jasarien** 2015-11-07 00:04 UTC
