### ISSUE TITLE
Provenance on apple tv os10 and using 8bitdo nes30 pro controllers

### ISSUE THREAD

**Issue by fluxshinryu** [jasarien/Provenance#428] opened 2016-10-07 03:41 UTC
Hello guys,

New developer here learning on the fly. I have read many of your threads and was unable to find information about 8bitdo controllers working on apple tvos 10 through provenance. I have concluded that it works on ios with 1.2.5 and that version isnt available on tvos. Considering we now have the choice to use bluetooth keyboards (only in icade mode and sadly only one and not 2 controllers) i was wondering if anyone found a way to use the 8bitdo controllers on provenancetv. Either by using some sort of 3rd party software or a workaround in thr version itself. I hope eventually we will be able to, but i was curious if someone figured out a way on the apple tv.

Thanks again for your support and excellent job on provenance, it is a remarkable piece of software

**Comment by jasarien** [comment] 2016-11-01 23:45
Duplicate of #269

**Closed by jasarien** 2016-11-01 23:45 UTC
