### ISSUE TITLE
MFi Controller DPad Too Insensitive

### ISSUE THREAD

**Issue by KalenXI** [jasarien/Provenance#176] opened 2015-11-04 11:13 UTC
I can't speak for other controllers but on my Horipad Wireless MFi controller with the deadzone on the DPad currently set such that xAxis or yAxis has to be above or below 0.5 or -0.5 to trigger a button press it means you have to press down fairly hard on the DPad before it does anything. Much harder than how hard you have to press to navigate the iOS interface. I disabled the deadzone so that the DPad buttons act similarly to how the A/B/X/Y buttons where any pressure at all results in a button press and the responsiveness is much improved. However if there was a good reason for having a deadzone on the DPad like certain controllers not fully returning to 0 when not being pressed then you might want to at least lower the threshold to 0.1.

Example code:

    if (xAxis != 0)
        {
            if (xAxis > 0)
            {
            [snesCore pushSNESButton:PVSNESButtonRight forPlayer:player];
            [snesCore releaseSNESButton:PVSNESButtonLeft forPlayer:player];
        }
        else if (xAxis < 0)
        {
            [snesCore pushSNESButton:PVSNESButtonLeft forPlayer:player];
            [snesCore releaseSNESButton:PVSNESButtonRight forPlayer:player];
        }
    }
    else
    {
        [snesCore releaseSNESButton:PVSNESButtonRight forPlayer:player];
        [snesCore releaseSNESButton:PVSNESButtonLeft forPlayer:player];
    }
    
    if (yAxis != 0)
    {
        if (yAxis > 0)
        {
            [snesCore pushSNESButton:PVSNESButtonUp forPlayer:player];
            [snesCore releaseSNESButton:PVSNESButtonDown forPlayer:player];
        }
        else if (yAxis < 0)
        {
            [snesCore pushSNESButton:PVSNESButtonDown forPlayer:player];
            [snesCore releaseSNESButton:PVSNESButtonUp forPlayer:player];
        }
    }
    else
    {
        [snesCore releaseSNESButton:PVSNESButtonDown forPlayer:player];
        [snesCore releaseSNESButton:PVSNESButtonUp forPlayer:player];
    }

**Comment by jasarien** [comment] 2015-11-04 11:26
Duplicate of #168. Please read other issues before creating new ones to minimise duplicates. This issue is planned to be solved with a user configurable deadzone, since it was added because most other controllers are too sensitive. Please read the comments in the linked issue.

**Closed by jasarien** 2015-11-04 11:26 UTC

**Comment by KalenXI** [comment] 2015-11-04 11:31
Sorry about that. I searched for "sensitivity" and "dead zone" but didn't find any issues so I must've missed the existing issue report.
