### ISSUE TITLE
Minimize Systems in Library Menu

### ISSUE THREAD

**Issue by addicted131** [jasarien/Provenance#299] opened 2016-03-10 04:49 UTC
I just purchased a BuildStore subscription for your app. I must say thank you for this amazing application. It is fantastic, however i have a few drawbacks it seems. I am using an iPod Touch 5 and the screen is very small, scrolling is also a bit slow due to low system memory. I was wondering if it would be possible to minimize the system subsections into a single system name. So i can quickly choose one system then browse through that system only, rather than having to scroll completely through all the other systems to access the one I wish to play. Also, is there a search function planned for the future ? Thank you again.

**Comment by jasarien** [comment] 2016-03-16 15:21
Duplicate of #3

**Closed by jasarien** 2016-03-16 15:21 UTC
