### ISSUE TITLE
tvOS - Change Artwork and Name of Games

### ISSUE THREAD

**Issue by dhmartin82** [jasarien/Provenance#220] opened 2015-11-20 18:42 UTC
Is there a mechanism to edit names and apply custom artwork to the games in the tvOS library like iOS? I have several mislabeled titles I'd like to fix. Thanks.

**Comment by jasarien** [comment] 2015-11-20 18:56
Nope.

Duplicate of #173

**Closed** 2015-11-20 18:57 UTC
Labels: Duplicate
