### ISSUE TITLE
Add frameskip for GBA?

### ISSUE THREAD

**Issue by nsuchy** [jasarien/Provenance#593] opened 2017-09-07 16:21 UTC
Could you guys add in a toggle to enable frameskip for GBA games? Despite being an emulator that Xcode will compile without errors (great job on this, GBA4iOS was a nightmare to try and compile which is why I'm switching) the audio can sometimes get skippy. Thoughts?

**Comment by sevdestruct** [comment] 2018-03-07 10:40
This is a duplicate of #545 and similar reports that I think have been taken care of with recent improvements so I'm closing this unless it gets reported against the current dev builds or the upcoming 1.5 release

**Closed by sevdestruct** 2018-03-07 10:40 UTC
Labels: Emulator Core, Enhancement
