### ISSUE TITLE
Rename games

### ISSUE THREAD

**Issue by b-** [jasarien/Provenance#326] opened 2016-03-30 12:09 UTC
Sometimes Provenance's lookup isn't quite good enough (none of the SNES ROMS in my library have art or full titles), and sometimes it tries to be too smart for its own good (some alternate variants and beta versions of the same game show up as identical).

It would be so much easier if I could just manually rename a game.

**Comment by jasarien** [comment] 2016-03-30 13:10
Duplicate of #173

**Closed by jasarien** 2016-03-30 13:10 UTC
