### ISSUE TITLE
Not a new issue but though I would re visit it

### ISSUE THREAD

**Issue by Jerklife** [jasarien/Provenance#586] opened 2017-08-01 02:02 UTC
Thanks @jasarien for the great emulator, except it's actually not that great. at least not yet.

for some time, folks have been mentioning the lack of compatibility with Nimbus remotes and remapping of keys. however issues still persist 2-3 years later.

I have been doing some searching and it seems someone may have found a fix for the problem, I could be completely wrong seeing as how I have no idea how to code myself.

I came upon this old thread 
https://github.com/lesbird/MAME4apple-037b5/issues/18 

(In some Arcade game (like kof 97 , 98) , it need using B Button.
but press B Button will return to home menu.
I found a solution here can prevent return to home menu issue
I already try , its working)

in GameViewController.h

import <UIKit/UIKit.h>
#import <SpriteKit/SpriteKit.h>
#import <GameplayKit/GameplayKit.h>
++@import GameController;
++@interface GameViewController : GCEventViewController
--@interface GameViewController : UIViewController
@end

Can anyone out there help me try to do this for this build. please and thank you

**Comment by jasarien** [comment] 2017-12-19 23:57
The `PVEmulatorViewController` class already subclasses `GCEventViewController` on tvOS, so there’s nothing new here. The bug is still an issue and is caused by something I’m still yet to discover

Duplicate of #522

**Closed by jasarien** 2017-12-19 23:57 UTC
