### ISSUE TITLE
Save States not working with SuperMario RPG SNES

### ISSUE THREAD

**Issue by jonmcclay** [jasarien/Provenance#562] opened 2017-04-08 14:04 UTC
Verified with 2 different working files for SuperMario RPG. I can save a state, but loading does nothing.

Verified this is not a problem with other iOS emulators.

**Comment by davidbdeath** [comment] 2017-06-06 05:09
I had the same issue with mega man x2 just a minute ago.

**Comment by Canadadry** [comment] 2017-11-07 08:56
And I hace the same issue with zelda and metroid

**Comment by jasarien** [comment] 2017-12-20 00:58
Duplicate of #552

**Closed by jasarien** 2017-12-20 00:58 UTC
Labels: Bug, Emulator Core
