### ISSUE TITLE
DPad Sizing

### ISSUE THREAD

**Issue by dunkle93** [jasarien/Provenance#472] opened 2016-12-03 02:29 UTC
I was just wondering, how do you resize the dpad in code? I'm just trying to play tecmo bowl and nhl 94 it feels tough using diagonal directions.

**Comment by dunkle93** [comment] 2016-12-03 02:30
I'm new at this stuff and using an iPhone 7 and the dpad feels big to use

**Comment by jasarien** [comment] 2017-12-20 01:28
Duplicate of #25

**Closed by jasarien** 2017-12-20 01:28 UTC
