### ISSUE TITLE
Cannot Fix Missing or Incorrect Box Art -- No UI to Correct

### ISSUE THREAD

**Issue by LeftoverNoodles** [jasarien/Provenance#284] opened 2016-02-11 03:52 UTC
Multi-region games like Dr. Mario for the NES and romhacks, like Flames of Eternity can have missing or incorrect box art.   The US/JP Verion of Dr. Mario shows the Famicom box, FoE will show no box art.  Additionally some games like Mega Man 3 for the NES will only download box art when uploaded in a ZIP file.  Uploading the same file as "Mega Man 3 (USA).nes" will not properly display the art.

**Comment by pmp174** [comment] 2016-02-11 10:48
Your supposed to press down on it until a field comes up allowing you to change the art.

**Comment by LeftoverNoodles** [comment] 2016-02-11 17:53
Press down on what?  Where?   I am using the TVOS Build.  Ver 1.2.6.

On the library if I press and hold the track pad on the remote or the a button on a controller I get an options menu with delete or cancel.  Launching the ROM and hitting menu brings up another set of options but with nothing taking about art.

**Comment by pmp174** [comment] 2016-02-11 19:05
@LeftoverNoodles I thought you were talking about the mobile app. I believe it was mentioned that there still isn't an interface for that yet.

**Comment by apexad** [comment] 2016-02-11 19:22
duplicate of #173

**Comment by jasarien** [comment] 2016-02-13 18:51
There's still no sign of any asset catalogue API in tvOS 9.2 beta, so there's still no way to pick an image from a photo library to use as cover art replacements. So as @apexad said, this is a duplicate of #173

**Closed by jasarien** 2016-02-13 18:51 UTC
