### ISSUE TITLE
Moving touchpads

### ISSUE THREAD

**Issue by DanyaelthekidRS** [jasarien/Provenance#658] opened 2018-01-18 19:26 UTC
Can you add a feature to where you can move the touchpads on the screen. The way they are placed it's very awkward and it's hard to play with when you are trying to do the Sonic 3 & knuckles blue sphere special stages

**Comment by jasarien** [comment] 2018-01-18 21:29
Duplicate of #25

**Closed** 2018-01-18 21:29 UTC
Labels: Duplicate
