### ISSUE TITLE
Problems on Iphone 7 +

### ISSUE THREAD

**Issue by Raynords** [jasarien/Provenance#480] opened 2016-12-14 16:08 UTC
After several tests, I notice freezes with repetition and big problem with the sound (sound that cuts and that sizzles) on the emulator SNES.
I repeat the test on my Mini 4 Ipad and no problem of kind.

**Comment by jasarien** [comment] 2016-12-14 16:11
Dupe of #417

Have you tried the latest version?

**Closed by jasarien** 2016-12-14 16:11 UTC

**Comment by Raynords** [comment] 2016-12-14 16:48
Yes it is the last version that I use
I tried to uninstall and re-install and try several Roma and I have always the same problem of freeze and sounds

**Comment by Raynords** [comment] 2016-12-14 16:51
de plus les controles se retrouve au millieu de l'ecran au lieu de se trouver en bas.
