### ISSUE TITLE
B Button Triggers App Menu on SteelSeries Nimbus with AppleTV 4

### ISSUE THREAD

**Issue by bastardsby** [jasarien/Provenance#522] opened 2017-01-28 22:37 UTC
Hi, first of all, thank you so much for all the work you've put into this beautiful app. I've been trying it out for the last couple of days and had a lot of fun playing old NES and Genesis games again.

I'm not sure if this is a bug with the emulator or something else, but the SteelSeries Nimbus' B button seems to trigger both the app menu (not the ROM's menu) along with the expected in-game B button behavior. For example, when playing Super Bomberman 3 for SNES, if I press the B button to set a bomb, the bomb will be set, but the app menu will also be brought up asking if I want to Return to Game Library or Resume. The Menu button on the Nimbus has the same functionality as the B button (which is also the case when navigating the AppleTV interface outside the Provenance app).

I'm using Provenance 1.3.2 on an AppleTV 4 running tvOS 10.1.1. This is my first time posting anything on GitHub, so apologies if the answer to this issue is obvious or if I left something out.

**Comment by zfisher323** [comment] 2017-02-04 21:31
I can confirm the exact same behavior on my steel series nimbus running 1.3.2.

**Comment by appletv4** [comment] 2017-02-05 14:54
Remove the app from the background and reopen

**Comment by TomR01** [comment] 2017-02-19 07:15
Yeah I have this problem too - is there a fix?

**Comment by bastardsby** [comment] 2017-02-19 19:01
@appletv4 I tried removing the app and reopening, but no luck.

**Comment by valdetero** [comment] 2017-02-28 15:40
I just installed it on my Apple TV and noticed the same issue.

**Comment by lolkthxbai** [comment] 2017-03-02 17:27
tvOS 10.1.1 Provenance 1.3.2 rev ec652bb
Nimbus Steelseries Ver. 1.6.3.1
I can't reproduce the issue. I added Super Bomberman 3 to my library and was able to place bombs (B Button) without the in app menu being triggered.
Update Provenance if you can and also update your controller using the Nimbus app from the AppStore. Try it again and post back your results.

**Comment by valdetero** [comment] 2017-03-02 18:32
@lolkthxbai I got latest right before I installed it 2 days ago. I'll see if the controller has an update.

**Comment by valdetero** [comment] 2017-03-03 03:06
I'm running tvOS 10.1.1, Nimbus 1.6.4.1, Provence 1.3.2 (659), Revision bc6a42a and it is a problem on Bomberman 3. I changed the iCade controller types but it didn't seem to make a difference. Should the Nimbus be Standard or SteelSeries Free?
Are you using older versions than me?

**Comment by lolkthxbai** [comment] 2017-03-03 03:57
@valdetero You're version of Provenance is outdated, mine shows 1.3.2(672) on the iOS app. I'll let you know what the Apple TV version says. I use the  Nimbus SteelSeries sold by Apple and BestBuy. It looks like there's a minor version difference on the controller though, I'll check that as well when I get home.

**Comment by lolkthxbai** [comment] 2017-03-03 03:58
@valdetero btw, which localization of Super Bomberman 3 are you using? I'm using the European one.

**Comment by bastardsby** [comment] 2017-03-03 04:01
I'm using the USA localization. I used Bomberman as an example, but the problem exists when using other games. Bomberman is just one example where the issue really gets in the way of being able to play the game since the B button is used so often.

**Comment by lolkthxbai** [comment] 2017-03-03 04:30
@bastardsby hmm that's very strange
Can you build and run Provenance while connect to a Mac, reproduce the issue a few times and post your console log here?

**Comment by jasarien** [comment] 2017-03-03 05:40
The Steelseries Nimbus is not an iCade controller it is an MFi controller. You shouldn't be setting any iCade settings when using it. 

Try quitting the app totally (remove it from the multitasking view) and trying again without touching any iCade settings. 

It's a hunch, but I think it's possible that paying with the iCade settings when not using an iCade controller is causing issues. I will have to look into it.

**Comment by lolkthxbai** [comment] 2017-03-03 09:30
I can understand now what @valdetro meant by SteelSeries Free, it's an option in the iCade settings. I haven't touched it at all because I have a (MFi) Nimbus SteelSeries, not the Free model. So I set iCade to SteelSeries Free and sure enough, the B button on my controller opens the in-app pause menu. So @jasarien is right.

**Comment by QuarterSwede** [comment] 2017-03-03 11:23
Maybe there should be a message in the iCade settings that mentions the Steelseries Nimbus. Something like "if using a Steelseries Nimbus leave iCade off" since multiple people have mistakenly associated the Free with the Nimbus.

**Comment by valdetero** [comment] 2017-03-03 20:04
I think just putting a message saying not to use iCade with MFI devices. Or make the option the off option to include MFI.

**Comment by jasarien** [comment] 2017-03-03 23:45
Possibly. I'd rather fix the actual issue though, since it should be possible to use an iCade and an MFi controller together at the same time for multiplayer.

**Comment by appletv4** [comment] 2017-03-09 02:25
I don't feel sorry for you guys , I upgraded from the trash MFI controllers and I'm now in retro heaven with an snes30 8bitdo controller 
It was tough at first after spending $100 on 2 MFI controllers (nimbus/horipad) but after months of using the snes clone controller  the Apple TV became my primary retro gaming machine , previously had an ouya (sold it) ,vitatv (yes you can play emulators on this but I hate retroarch ), nvidia shieldtv(sold it) 


I still have the horipad controller for the rare occasion I will play an Apple TV game , I say rare cause it's been months since I used it

**Comment by clementbarry** [comment] 2017-03-27 03:27
Issue confirmed here too, with Nimbus controller and all things latest. Disabling iCade and restarting Provenance from App Switcher circumvented the issue. Will update again after receiving my ordered 8bitdo SFC30...

**Comment by clementbarry** [comment] 2017-04-16 07:16
So after pairing an 8bitdo SFC30 controller in addition to a Nimbus controller, I confirm the Nimbus B button triggers app menu, thus making 2-player games impossible in practice with this combination of controllers.

**Comment by jamieaquila** [comment] 2017-04-27 02:57
I'm able to duplicate this issue. Unable to play multiplayer with a Nimbus and any 8bitdo remote.

**Comment by chirikoa** [comment] 2017-05-02 04:30
I am also having the same issue. Provenance 1.3.2 on Apple TV 4. When using 8bitdo snes30 controller (iCade) for Player 1 and Nimbus for Player 2, the Nimbus is unplayable because the B button triggers the Provenance app menu. Begging for a fix!

**Comment by disciple-3** [comment] 2017-07-29 04:27
I have the latest version and I'm having this issue...any resolutions yet?

**Comment by palla89** [comment] 2017-08-27 22:08
News about this problem?

**Comment by sala91** [comment] 2017-09-04 20:51
Can replicate issue. Makes usability really bad. Workaround proposed in thread worked - disable icade, restarted app, opend game, disabled icade again, seems all is working for now.

**Comment by jasarien** [comment] 2017-12-20 00:35
I believe this to be fixed in the latest version 6615d9f9ff832b8722f426d4d5b3a641ca668b42 

If this is still a problem for anyone after updating to Provenance 1.4, please reopen this issue.

**Closed by jasarien** 2017-12-20 00:35 UTC

**Comment by Kwant** [comment] 2017-12-23 00:30
The problem still occurs with version 1.4(829) , running on tvOS 11.2.1 with the (nimbus,8bitdo) combination. Both controllers work fine on their own. When both controllers are connected the nimbus closes the app on pressing the b button. Restarting provenance from the app switcher did not circumvent the problem.

**Comment by jasarien** [comment] 2017-12-23 15:32
Hi @Kwant, please leave a comment on PR #628 -- we're noticing inconsistent behaviour between different setups.

**Comment by jasarien** [comment] 2017-12-23 15:40
I asked about this issue on Twitter and a helpful person mentioned that it is probably something interfering with the Focus Environment on tvOS. I think the iCade Reader View might be stealing focus (as it would need to do to intercept the key command sent by the iCade controller), so the pause handler in the emulator view controller doesn't receive the button press event (or the tap gesture recogniser event), because it's probably swallowed by by the iCade reader view. If we can confirm that this only happens with an iCade controller and MFi controller are connected, then we can start to narrow this down.

**Comment by jasarien** [comment] 2018-05-14 22:48
If you’ve enabled iCade mode while using an MFi controller, disable it and restart Provenance. ICade interferes with mfi controller input.

**Comment by leetaylor** [comment] 2018-06-06 11:40
Wild theory, I don't think the problem is with Provenance... just got my hands on the Nimbus and the B button is acting like a back button right through tvOS.

**Comment by falkboman** [comment] 2021-09-07 19:32
I got this issue too 👍 I have only one controller (+ Siri remote), tried first without iCade, then with, without again, restarted app, tried both main and beta-versions. Can't play any games where B-button is used, also the "house"-button triggers Apples TV-menu (from the right).
--------------
tvOS 14.7
Provenance 1.5 Beta (and 1.4)
Controller: Nimbus+

**Comment by JoeMatt** [comment] 2021-09-09 03:58
We're on 2.0 and this is fixed.
