### ISSUE TITLE
Add Dropbox support to sync savegames

### ISSUE THREAD

**Issue by josejulio** [jasarien/Provenance#71] opened 2015-06-10 16:16 UTC
It would be great to have dropbox support (or google drive, copy, etc) to sync the saved games (or even the roms!) for playing with multiple devices (ipad / iphone for example)

**Comment by jasarien** [comment] 2015-06-10 16:20
Duplicate of #1 

Please don't raise duplicate issues. Search the other issues before raising new ones.

**Closed by jasarien** 2015-06-10 16:20 UTC

**Comment by josejulio** [comment] 2015-06-10 16:22
Sorry @jasarien, i though it wasn't here, I'll do a search next time.
