### ISSUE TITLE
Question about: Moving and resizing contorller layout

### ISSUE THREAD

**Issue by levantdekruz** [jasarien/Provenance#584] opened 2017-07-17 00:04 UTC
First off I want to say Thank you @jasarien found your programed and it has been a blessing and half for my mother she loves gaming and inspired me to game as well and due to arthritis she can't hold a controller anymore. So thank you for your time and all your hard work man you are amazing. 

My question is I'd like to resize and move the buttons on the ipad screen she plays on so it's a bit easier for her. I'm sorry if this was discussed and I just missed it. Been looking through this for two hours and finally said you know what I'll just ask. If it is in here can you please tell me how to do it. Thank you for your time you are much appericated and have a blessed day,
levant

**Comment by Jerklife** [comment] 2017-08-01 01:54
I Second this, this has been an issue since the beginning of the making of this app it seems and the developer just seems to ignore this issue.

I wish I knew anything about coding, I would try to resolve myself.
after searching for a resolution I came upon this here, but do not have the smarts to pull it off myself.

--- 
In some Arcade game (like kof 97 , 98) , it need using B Button.
but press B Button will return to home menu.
I found a solution here can prevent return to home menu issue
I already try , its working.
in GameViewController.h

import <UIKit/UIKit.h>
#import <SpriteKit/SpriteKit.h>
#import <GameplayKit/GameplayKit.h>
++@import GameController;
++@interface GameViewController : GCEventViewController
--@interface GameViewController : UIViewController
@end 
---------

Can anyone out there help me try to do this for this build. please and thank you

**Comment by beyondthetech** [comment] 2017-11-10 04:08
I'd like to add that I was able to build this for my iPhone X and while it plays great, the some of the buttons are either off the screen, in the "notch" area, and/or right next to the Home Indicator.  Is there a quick way to adjust these?  Where in the code can I find it if there's no layout editor?

**Comment by jasarien** [comment] 2017-12-19 23:59
Duplicate of #25

**Closed by jasarien** 2017-12-19 23:59 UTC
