### ISSUE TITLE
Provenance Appl Installation Failed

### ISSUE THREAD

**Issue by elbarbari** [jasarien/Provenance#294] opened 2016-02-28 14:17 UTC
Hi,

First, Provenance and Mame stopped working all the sudden. I have no idea why. So I tried to re-build Provenance without success.

In the bundle ID, I tried different names, and added numbers, but still get this same error. I get App Installation failed.

"This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique."

Please help

**Comment by JerGitHub** [comment] 2016-02-28 14:48
Your first issue is because of #292

**Comment by jasarien** [comment] 2016-03-03 15:04
Dupe of #292

**Closed** 2016-03-03 15:03 UTC
