### ISSUE TITLE
Scanline Support

### ISSUE THREAD

**Issue by maddox** [jasarien/Provenance#159] opened 2015-10-28 15:23 UTC
Support for scanlines would be most welcomed. I'm not sure how the core of Provenance works, but implementing this with either a filter, or even a simple UIImageView overlay would work well.

Scanlines helps everything look much better at larger resolutions, especially ones used via tvOS.

**Comment by jasarien** [comment] 2015-10-28 15:25
Duplicate of #54

**Closed by jasarien** 2015-10-28 15:25 UTC

**Comment by maddox** [comment] 2015-10-28 17:54
@jasarien Thanks! Sorry about that. I even perused all the issues before I opened that. My bad.
