### ISSUE TITLE
SteelSeries Nimbus controller D-pad problem

### ISSUE THREAD

**Issue by appletv4** [jasarien/Provenance#204] opened 2015-11-10 21:37 UTC
this is the official apple tv controller so a lot of people are going to buy this one,
it has a problem with Provenance and the dpad, you have to push really hard on the dpad to move in the game, the controller is not defective
in other apple tv apps like "cosmos" you gently  hold right on the dpad and it moves slowly to the right, you push harder and it moves faster to the right
in the Rayman Adventures you can gently push down on the dpad and the character moves fast

can you you make it so that in Provenance we don't have to push down hard on the dpad to move, the thumbsticks work great 
the dpad is the problem

thanks

**Comment by basvroegop** [comment] 2015-11-10 21:48
Yep, it's annoying. Already an issue for it here: https://github.com/jasarien/Provenance/issues/168

**Comment by jpete24** [comment] 2015-11-10 22:11
I just tested the recent update for this. Seems to work well once you
manually drop the sensitivity on the new menu option that @jasarien created.

On Tue, Nov 10, 2015 at 3:48 PM, Bastiaan Vroegop <notifications@github.com>
wrote:

> Yep, it's annoying. Already an issue for it here: #168
> <https://github.com/jasarien/Provenance/issues/168>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasarien/Provenance/issues/204#issuecomment-155577323>
> .
>



-- 
Josh Petersen
jpete24@gmail.com
515-450-7311

**Comment by jasarien** [comment] 2015-11-10 22:23
Dupe of #168 and already fixed with the configurable DPad deadzones. Please read other issues before raising duplicates.

**Closed by jasarien** 2015-11-10 22:23 UTC
Labels: Duplicate

**Comment by appletv4** [comment] 2015-11-10 23:25
thanks, i was using version 1.2.2
i didn't update because the release notes for 1.2.3 and 1.2.4  didn't mention  a fix for deadzone on dpad

after updating now i see the deadzone option in settings,but the app still says 1.2.2

**Comment by appletv4** [comment] 2015-11-10 23:28
edit: i see it now it was fix on 1.2.3

**Comment by basvroegop** [comment] 2015-11-11 06:39
Didn't realize the fix was deployed either, awesome news!
