### ISSUE TITLE
iOS 9.3 adds support for BT keyboards on Apple TV 4

### ISSUE THREAD

**Issue by samadulator** [jasarien/Provenance#269] opened 2016-01-11 21:02 UTC
Apple has released a developer preview of iOS 9.3 which hails the return of Bluetooth keyboard support for Apple TV. Since that will be a thing again, do you think we can add iCade controller support to the Apple TV version of Provenance?

It would be a HUGE win to be able to use the SNES30/other 8bitdo/iCade controllers on the Apple TV instead of an MFi controller.

**Comment by basvroegop** [comment] 2016-01-11 21:20
Oh man, I'd love this. Already bought a Steelseries Nimbus, but I'd totally get some SNES30's to go along with it.

**Comment by samadulator** [comment] 2016-01-11 21:24
I stand corrected, it's tvOS 9.2. But yes, I agree with you. Here are the details:

http://www.macrumors.com/2016/01/11/apple-first-tvos-9-2-beta/

**Comment by DanielFontes** [comment] 2016-01-18 22:06
Good News: AppleTV and 8bitdo (iCade) is working fine with tvOS 9.2
Bad News: Only in debug mode so far

**Comment by gingerbeardman** [comment] 2016-01-18 23:16
@DanielFontes nice work! way to go.

**Comment by appletv4** [comment] 2016-01-19 03:21
@DanielFontes can I go ahead and buy the nes30 pro ?

**Comment by samadulator** [comment] 2016-01-19 06:41
Phenomenal! Now I can get a new AppleTV!

**Comment by DanielFontes** [comment] 2016-01-20 14:51
@samadulator At the moment it's no fun to play because of the lagging described here: https://github.com/jasarien/Provenance/issues/157

**Comment by innersuck** [comment] 2016-01-23 03:23
So... Can i huy the snes30 ?.. Ir will works eventually?

**Comment by innersuck** [comment] 2016-01-23 14:25
@DanielFontes, so the game pads from 8bitdo will work with this update?... Or it has to be done some work?.. The update is TvOS 9.3?

**Comment by epohs** [comment] 2016-01-24 03:48
Aside from the lag, what other limitations are there to using the nes30 pro in icade mode on the Apple TV?

**Comment by appletv4** [comment] 2016-01-24 04:18
@epohs I think so far the 8bit controllers only work in this provenance 
Not other apps , so you will be buying it just fot this

**Comment by Bigperm1** [comment] 2016-01-29 19:18
I updated my Apple tv 4 to TVos 9.2 (13Y5189e) and lost my Provenance app, am I screwed or is there a fix. It worked perfectly on 9.1.

**Comment by jasarien** [comment] 2016-01-29 19:21
If you did a straight update then it should have left the apps alone. It sound like you did a restore. You can reinstall the app, but your saves and ROMs are probably gone.

**Comment by samadulator** [comment] 2016-01-29 19:26
Yeah, it sounds like you performed a restore instead of an update, or something went seriously wrong during the update and your data got hosed. Did you have to set up the Apple TV like a new one after updating or did it go right to the home screen?

—Samad

**Comment by Bigperm1** [comment] 2016-01-29 19:27
Wow thank you for the rapid reply!! I have tried multiple times, I get this error.


I just loaded kodi on it with no problems.

**Comment by Bigperm1** [comment] 2016-01-29 19:29
This is the issue:
ld: warning: object file (/Users/jeffmorton/Library/Developer/Xcode/DerivedData/Provenance-guoapdjaqjpafjfjlkoykekkphrs/Build/Products/Release-appletvos/libPVSupportTV.a(OEGameAudio.o)) was built for newer tvOS version (9.1) than being linked (9.0)

Yes i did a full restore.

**Comment by jasarien** [comment] 2016-01-29 20:03
Well the full restore explains why the apps are gone. 

The issue you posted is just a warning. Does the build not install? Are there any other errors? A warning should not prevent the all from installing.

**Comment by Bigperm1** [comment] 2016-01-29 20:44
That's all I'm getting but 201 of them (all the same) it doesn't say build succeeded.

**Comment by ramone12781** [comment] 2016-02-05 23:25
Dear Developer,

I know you have responded to this question before but lets set aside the ego and reasoning behind why you don't want to incorporate fullscreen mode and how there are quite a few people who would like it so why not let the people have a choice? We all appreciate your hard work and all that goes into a great program such as yours. But I am pleading with you to please add the fullscreen option for us Poor Ol' School users that can't stand the sight of a 4:3 aspect ratio... 

Thank You

**Comment by Bigperm1** [comment] 2016-02-06 01:24
You sent this to the wrong person.

**Comment by ramone12781** [comment] 2016-02-06 01:32
nah i posted in here because I seen Jasarian was in this thread not too long ago so was hoping to get his attention. Guess I coulda made my own thread... My bad.

**Comment by gingerbeardman** [comment] 2016-03-21 20:53
So 9.3 final is out, but the load screen says "supports Apple Wireless Keyboards". Are we out of luck with iCade support?

**Comment by pmp174** [comment] 2016-03-21 21:48
@gingerbeardman it supports all keyboards. don't be too specific with apple, its just advertising. Ive connected my steel series free (icade controller) and the apple tv recognizes it and it types the keys on the screen. If provenance brings back support for it, the icade will work.

**Comment by leolobato** [comment] 2016-07-16 18:07
I've been investigating this on tvOS 9.2.1 and it doesn't appear to be possible so far. The way we handle iCade input is not currently supported and apparently we can't hide the on-screen keyboard while still intercepting the iCade key presses.

**Comment by appletv4** [comment] 2016-07-16 18:48
Thanks Leo , 

Just this week I bought a horipad ultimate , my second mfi controller 
I didn't like the dpad on the nimbus 

This horipad controller has the best dpad I've ever used since early Nintendo controllers , even better than 8bitdo controllers 

So if your looking for a controller for provenance get the horipad over the nimbus for retro gaming on the Apple TV

**Comment by ramone12781** [comment] 2016-07-16 20:01
Off topic but is there any way to make prov go fullscreen?

**Comment by jsarch527** [comment] 2016-11-23 07:39
@DanielFontes I downloaded your must recent build of Provenance that has attempted to icade support for tvos.  I can't seem to get my 8bitdo snes30 controller to work with it despite pressing buttons as other people have noted.  Any tips - I'm running tvos 10.  The controller is connecting the the apple tv via icade - if i go to the search box and press keys, a bunch of letters come up.  It doesn't show up as an option when I attempt to select a controller for player 1, but it does say 'or press a button on your icade controller'.  Nothing happens.

And no luck getting anything to happen in a game.  I'll probably end up getting a mfi controller as many have recommended, but thought I'd give the snes controller at least a couple go's before writing it off.  

Any advice/help would be appreciated.  Thank you all!

**Comment by leolobato** [comment] 2016-11-23 07:41
Still not supported as the comments above mention, @jsarch527 -- and it's unlikely it will be supported.

**Comment by DanielFontes** [comment] 2016-11-23 08:06
@jsarch527

There is still a bug in the iCade stuff but I was too lazy to fix it. When your controller works in other inputs but not in Provenance just hide Provenance with the Home button and jump into it again. I have the same problem 😉

**Comment by jsarch527** [comment] 2016-11-24 04:08
@DanielFontes No luck with your technique.  Are there any tips for what settings to use in the controller settings?  I've tried various combinations of remote/not playing for the controller settings and standard controller/nes30 for the icade settings.  Text shows up in the search when i push buttons, but when it comes to a game, nada.

If you got any more advice, let me know.  If not, I'll keep an eye out in case there are any future updates, cheers!

**Comment by DanielFontes** [comment] 2016-11-24 09:01
@jsarch527 I ma going to upload a short video tutorial how it's working later that day. It shouldn't be that hard 😉

**Comment by jsarch527** [comment] 2016-11-24 13:39
@DanielFontes Thanks for this!  i was pressing buttons on the controller when it comes to selecting the controller yesterday to no avail.  Of course after watching this video, now it works!  However I've got a new problem - the buttons are mapped to what they should be - the L shoulder makes mario do his spin attack in Super Mario World, select is jump and A is what the start button should be.

I'm about to leave for a trip and won't be back until next week so I won't be able to play around with it more, but I'm a lot further along that I was.  Thanks for that and if you have any advice on the buttons, let me know!  Cheers.

**Comment by gingerbeardman** [comment] 2016-11-24 14:19
@jsarch527 what controller are you using? can you post USB or BT info for it?

**Comment by appletv4** [comment] 2016-11-24 15:44
@danielfontes this works on release mode and with no lag now ?

**Comment by jsarch527** [comment] 2016-11-24 19:29
@gingerbeardman I am pretty certain I set the controller properly to icade (start + a).  It is running the most recent 8bitdo firmware (2.70) if that matters.  I will try some more when I get back from the holiday.  I definitely feel like I'm this close to getting it to work, excited to play the emulator with the near original controller.

**Comment by and01** [comment] 2016-11-29 09:11
@DanielFontes Sweet. Works like a charm and with no lags whatsoever. The one feature I have been waiting for a while now. Thx for you work.

**Comment by appletv4** [comment] 2016-11-30 19:33
after months of not using the sfc30 controller, i leave it charging overnight, i install fontes provenance fork  and the controller is dead , no lights come on no matter what i press

**Comment by jsarch527** [comment] 2016-11-30 23:13
@gingerbeardman I disconnected the controller and started the whole bluetooth pairing thing again, followed the video by @DanielFontes and now it works like a charm - not sure what the glitch was.  I did take the firmware on the controller from 2.70 to 2.68 (which is what it shipped with).  Thanks all for all the hard work everyone - this setup works great!

**Comment by dasilvetz** [comment] 2016-12-02 18:08
Hi - I've watched the video, can't get my nes30 to be recognized in provenance 1.3 on Apple TV.

The issue is that I'm not seeing the iCade option at all in the Provenance settings.. yet the controller is paired to the Apple TV and tapping buttons on the controller indeed brings up random characters in search (like shown in the above video).. not sure what to do :(

**Comment by and01** [comment] 2016-12-02 18:22
@dasilvetz you need to get the fork by @DanielFontes 
https://github.com/DanielFontes/Provenance
after deploying you should see the icade option in the menu..

**Comment by dasilvetz** [comment] 2016-12-02 18:26
Thank you, I realized that right after submitting the comment :) I'll try that now, fingers crossed!

**Comment by JoeMatt** [comment] 2016-12-02 18:43
What's keeping this from being a PR? Are there outstanding bugs?

I just got an nes30. I'd be interested in taking a look.

**Comment by dasilvetz** [comment] 2016-12-02 19:00
So I finally got the 1 controller to work and it's awesome (thx!) unfortunately my 2nd nes30 controller can't connect to the Apple TV :/ is there a workaround to use two iCade controllers simultaneously with Provenance ?

Thx!

**Comment by Hanterdro** [comment] 2016-12-02 20:58
@DanielFontes 

Cool, thank you for your work!

Do you plan to support two iCade controllers?
And can you bring you your changes back to the official Provenance code? Why a fork?

**Comment by appletv4** [comment] 2016-12-02 22:32
My sfc30 controller is dead
 
Do you guys recommend the nes30 or nes30 pro ? 

I'm thinking of getting this because I have an nes classic , but don't want to wait that long 
https://www.amazon.com/8Bitdo-NES30-Classic-Set-NES/dp/B01MTQ9QPB/ref=sr_1_2?ie=UTF8&qid=1480717738&sr=8-2&keywords=8bitdo+nes+classic


@JoeMatt I tested this fork using a mfi controller and still has some bugs , when your in a game hitting menu doesn't bring up the option pop up "reset game and orthers"  it takes you back to game selection

**Comment by appletv4** [comment] 2016-12-09 05:48
Are the controls mapped out correctly for the nes30 ? 

http://www.nes30.com/images/nes30-1.jpg

For example in super Mario bros nes is "y" run & "b" jump ?

**Comment by jsarch527** [comment] 2016-12-14 23:36
@Hanterdro I take it only one icade controller is supported at the moment?  I only have one, but was thinking of getting a second.  Sounds like a may need to rethink that...

**Comment by appletv4** [comment] 2016-12-17 19:34
Update got my nes30 controller and works really good 
And the menu pop up now works when the icade controller is connected 


@DanielFontes please add this to a pull request or merge to the latest provenance for dark theme support 


@jasarien you really need to get one of these 8bitdo controllers now that it works on the Apple TV 
Is so much better than the MFI controllers , is like playing with a real  nes or snes controller , worth the $35

**Comment by nasredin** [comment] 2016-12-23 06:17
hi,
this is  1st version which really works on my atv4  with my nes30 pro :) very good job, @DanielFontes! 

i have one issue, down direction is pressed after a while of playing(1 minute or so),  also left, right directions stops work at same time. Anybody same experience?

**Comment by appletv4** [comment] 2016-12-23 06:37
@nasredin I've seen that problem on MFI controllers and provenance when I use the thumbsticks 

But not on the nes30 with no thumbsticks 

What firmware is your controller on ?
http://www.8bitdo.com/nes30pro/Firmware.html

**Comment by nasredin** [comment] 2016-12-23 09:01
@appletv4 thx4reply, yes i'm on latest 1.71 :) everything works very nice first couple minutes...

**Comment by appletv4** [comment] 2016-12-27 16:17
The snes30 is on sale here for $20 plus $5 shipping 

https://shop.xgaming.com/collections/retro-game-accessories/products/snes-wireless-gamepad-for-pc-mac-ios-android

**Comment by pkamb** [comment] 2016-12-28 07:52
I rebased those changes on top of the latest Provenance master and opened a PR, should be resolved and ready for code review / merge:  
  
https://github.com/jasarien/Provenance/pull/493

**Comment by jasarien** [comment] 2016-12-29 15:02
This appears to be fixed by PR #493.

**Closed by jasarien** 2016-12-29 15:02 UTC
Labels: Controllers, Enhancement, tvOS
