### ISSUE TITLE
PSX Games cut off (Iphone 8 Plus)

### ISSUE THREAD

**Issue by oCSnow** [jasarien/Provenance#674] opened 2018-02-04 16:15 UTC
Game is cut off right side.

Any clue i can i fix it?

Keep up the good work and thank you for the reply

![img_0058](https://user-images.githubusercontent.com/36102219/35779543-e74f9490-09ce-11e8-8983-75fe8d3336f9.JPG)

**Comment by JoeMatt** [comment] 2018-02-05 01:00
Looks like yo're running the branch with the CRT filter. Some fixes were just pushed to master after this bug was submitted. Pull and rebuild and report back if it's resolved.

**Comment by braindx** [comment] 2018-02-06 20:03
Yes, this should be fixed at head.

**Comment by jasarien** [comment] 2018-02-19 21:20
@oCSnow Can you try with the latest code and verify if the issue is solved?

**Comment by oCSnow** [comment] 2018-02-25 19:52
@jasarien i've disable the CRT filter and now everything works fine. Thank you for the support!

**Closed** 2018-03-05 03:46 UTC
Labels: Bug, Graphics, Ready for Testing
