### ISSUE TITLE
8bitdo Zero doesn't work and crashes app

### ISSUE THREAD

**Issue by giliammc** [jasarien/Provenance#375] opened 2016-07-11 04:31 UTC
I have 1.2.6 in release mode. My 8bitdo zero wont work and if I put it in snes30 mode it crashes the app

**Comment by giliammc** [comment] 2016-07-13 14:56
my phone just died so i wont have a way to test anything.

**Comment by appletv4** [comment] 2016-07-13 15:25
More info here 
https://github.com/jasarien/Provenance/pull/313

**Comment by jasarien** [comment] 2016-07-23 16:43
Dupe of #313

**Closed by jasarien** 2016-07-23 16:43 UTC
