### ISSUE TITLE
Mame Support

### ISSUE THREAD

**Issue by eenlow** [jasarien/Provenance#265] opened 2016-01-05 02:14 UTC
I originally found out about you via Mame running on the Apple TV.  Are there plans to integrate Mame with this project or another?

Anything I can do to support the project please let me know.  I can code but a rookie.  But i can test and debug it needed.  I have a bunch of devices...

Thanks Love the project.  This old man can now play games on everything.

**Comment by jasarien** [comment] 2016-01-07 16:45
Duplicate of #152 #185

**Closed by jasarien** 2016-01-07 16:45 UTC
