### ISSUE TITLE
Blus Screen when running a ROM

### ISSUE THREAD

**Issue by Black959595** [jasarien/Provenance#664] opened 2018-01-21 21:40 UTC
You can watch this video 
https://streamable.com/9cr02

Can you help me please

**Comment by jasarien** [comment] 2018-01-21 21:43
Duplicate of #662 

Have you tried getting a different version of the ROM from another source?

**Comment by Black959595** [comment] 2018-01-21 22:15
I downloaded the Bin file and cue file separately from emuparadise .. then i merged them in one zip file

**Comment by jasarien** [comment] 2018-01-22 10:25
You downloaded them separately? Are you certain that the .CUE’s content matches the .BIN correctly? And that the binary image has the same track length, etc? It’s always best to obtain the BIN and CUE together as a single package so you can guarantee they’re compatible.

**Comment by Black959595** [comment] 2018-01-22 10:35
Ok thanks bro .. you were really helpful 👍

**Comment by jasarien** [comment] 2018-01-22 10:48
Closing as Duplicate of #662

**Closed** 2018-01-22 10:48 UTC
Labels: Duplicate
