### ISSUE TITLE
Game library flickering 

### ISSUE THREAD

**Issue by ghost** [jasarien/Provenance#249] opened 2015-12-20 16:48 UTC
The game library has moments where it deletes the game thumbnails and then starts flickering. This wouldn't be a problem but some roms are custom or aren't recognized by OpenVGB forcing me to have to reload the thumb nails one by one. This of course is just a minor issue but is something to look out for. IOS

**Comment by jasarien** [comment] 2015-12-20 16:51
iOS or tvOS?

**Comment by pmp174** [comment] 2015-12-20 16:51
IOS ( i was actually going to reedit and add that info)

**Comment by jasarien** [comment] 2015-12-20 16:57
Are you low on storage space?

**Comment by pmp174** [comment] 2015-12-20 17:07
I have 1.1 gb left which isn't much but it could explain why this is happening. Does iOS automatically delete those types of files on low storage?

**Comment by jasarien** [comment] 2015-12-20 17:09
Yeah the cover art is stored the cache which is emptied in low storage situations. I wouldn't have expected 1.1gb to be considered low though.

**Comment by pmp174** [comment] 2015-12-20 17:11
I don't think that explains the flickering either, though that could just be the library constantly refreshing.

**Comment by sevdestruct** [comment] 2018-03-07 08:22
I cannot reproduce nor have seen this bug. Can anyone reproduce this? Anyone experienced this in the 2 years and change since the original issue? Closing unless someone reports in.

**Closed by sevdestruct** 2018-03-07 08:22 UTC
Labels: Bug, User Interface
