### ISSUE TITLE
d-pad controller enhancement idea

### ISSUE THREAD

**Issue by jpbedoya** [jasarien/Provenance#731] opened 2018-03-08 09:32 UTC
Would it be possible to make the D-pad be a "floating" one like other games developed for touch devices? It will be a great enhancement for game play. Some examples: Mickeys Castle of Illusion, Dungeon Hunter, etc.
thx!

**Comment by sevdestruct** [comment] 2018-03-08 15:57
This is a duplicate of free-placing joystick and free-placing d-pad outlined in #718.

**Closed by sevdestruct** 2018-03-08 15:57 UTC
