### ISSUE TITLE
Crashing when starting PS1 ROM

### ISSUE THREAD

**Issue by KrypticFade** [jasarien/Provenance#642] opened 2018-01-04 16:43 UTC
Whenever I open a PS1 game, in my case Crash Bandicoot, Provenance keeps on crashing. It places the game inside the "PlayStation" section and the "Genesis" Section. I have downloaded BIOS files for PSX, also. I used this video to download Provenance: https://www.youtube.com/watch?v=MDbwTTUwUos 

A fix would be appreciated. Thank you.

**Comment by jasarien** [comment] 2018-01-04 17:13
Hey,

This seems to be a duplicate of #630 

Please read this guide on uploading PSX ROMs https://github.com/jasarien/Provenance/wiki/Playstation-Instructions

**Closed by jasarien** 2018-01-04 17:13 UTC
