### ISSUE TITLE
Feature Request: Cloud and P2P Synching

### ISSUE THREAD

**Issue by agonyou** [jasarien/Provenance#169] opened 2015-11-01 18:58 UTC
I noticed you have Realm in the source. Can I suggest to use Couchbase Lite?
Couchbase Lite can provide a  framework for synching docs and conflict resolution and peer to peer sync. Might be useful for owners of multiple devices. 

Austin

**Comment by jasarien** [comment] 2015-11-01 19:00
Duplicate of #1

**Closed by jasarien** 2015-11-01 19:00 UTC
