### ISSUE TITLE
Steelseries Nimbus lag when using Provenance with AppltTV4

### ISSUE THREAD

**Issue by Andi2k11** [jasarien/Provenance#235] opened 2015-12-07 17:23 UTC
HEllo

Im experiencing lag when using my Steelseries Nimbus. When playing SNES roms the controller dont react immediately. Pressing jump button you have to be a psychic and know beforehand when to jump.

Any one else experiencing this?

**Comment by jasarien** [comment] 2015-12-07 17:25
Read existing issues before creating new ones. Duplicate of #157

**Closed by jasarien** 2015-12-07 17:25 UTC
