### ISSUE TITLE
Portrait, Dropbox and n64

### ISSUE THREAD

**Issue by gun378** [jasarien/Provenance#68] opened 2015-05-21 21:08 UTC
Portrait and n64 would be great editions to provenance also Dropbox would mean I would not have to worry about losing all of my saved I I accidentally deleted it

**Comment by jasarien** [comment] 2015-05-22 13:41
Closing as duplicate of #31 and #1

No plans for N64 support currently.

**Closed by jasarien** 2015-05-22 13:41 UTC
