### ISSUE TITLE
menu options to switch buttons

### ISSUE THREAD

**Issue by giankdm** [jasarien/Provenance#263] opened 2016-01-04 17:49 UTC
A and B buttons follow the Gameboy Advance location convention (A is on the right, B is on the left). The mfi controller has a different location convention (A is always on the left, B is always on the right). This means that when the game says to press A, you have to press B instead, and viceversa. There could be a menu options to always map the A and B buttons (the main ones) to the console button letters.

**Comment by jasarien** [comment] 2016-01-07 16:46
Duplicate of #56

**Closed by jasarien** 2016-01-07 16:46 UTC
