### ISSUE TITLE
Lag in button input (steelseries nimbus)

### ISSUE THREAD

**Issue by z3r01** [jasarien/Provenance#229] opened 2015-11-28 14:29 UTC
games would have a delay effect when the button is pressed using the nimbus controller on the new Apple TV. On the iPad pro it's perfect , but noticed that on the atv4

**Comment by jasarien** [comment] 2015-11-28 14:33
Duplicate of #157

**Comment by jasarien** [comment] 2015-11-28 14:33
Also, ensure you're building with Release mode, if you're using Debug mode, then you're not following the [Build Instructions](https://github.com/jasarien/Provenance/wiki/Building-Provenance)

**Closed by jasarien** 2015-11-28 14:33 UTC
Labels: Duplicate

**Comment by drcreek** [comment] 2015-12-02 00:24
I had debug version installed. But just installed latest release. Still laggy with Nimbus.
