### ISSUE TITLE
[Request] Audio options, like allow background audio and mute

### ISSUE THREAD

**Issue by brianmcdoogle** [jasarien/Provenance#213] opened 2015-11-18 15:29 UTC
I'd love to be able to listen to music or podcasts while playing Provenance. Would it be possible to add audio options to allow background audio from other apps and then then to mute the game audio in provenance or change its volume so I could listen to an audiobook but hear a little game audio? Thanks!

**Comment by jasarien** [comment] 2015-11-18 16:37
dupe of #35

**Closed by jasarien** 2015-11-18 16:37 UTC
