### ISSUE TITLE
ROMs location on Server (NAS)

### ISSUE THREAD

**Issue by tvolponi** [jasarien/Provenance#271] opened 2016-01-17 01:16 UTC
This is a request, an enhancement,  instead of using the internal storage, why not just have all the ROMs on a NAS and just retrieve the ROM when needed. Thanks.

**Comment by jasarien** [comment] 2016-01-17 01:21
Duplicate of #1

**Closed by jasarien** 2016-01-17 01:21 UTC

**Comment by tvolponi** [comment] 2016-01-17 01:23
Sorry, didn’t reach #1. But thanks for the great memories, you brought back :)
