### ISSUE TITLE
8Bitdo FC30 Controller not recognized

### ISSUE THREAD

**Issue by txcx** [jasarien/Provenance#451] opened 2016-10-24 18:16 UTC
Tried out an 8bitdo FC30 controller and it is not recognized correctly.
Provenance v1.27
iOS 10.0.2

Works in other apps (correct recognized in bluetooth settings)

What's to do?

**Comment by jasarien** [comment] 2016-10-24 18:20
Dupe of #313

**Closed by jasarien** 2016-10-24 18:20 UTC
