### ISSUE TITLE
Resizing and rearranging the dpad and button controllers for Provenance 

### ISSUE THREAD

**Issue by Neatstar** [jasarien/Provenance#623] opened 2017-12-18 06:37 UTC
@jasarien thank you so much for Provenance. I really do love the emulator but it's really tough to play as of late since you're unable to move the Dpad controller or buttons in any position to feel more comfortable making whatever game you play feel uncomfortable. It would be really appreciated if this issue is being worked on. But other than that great emulator

**Comment by jasarien** [comment] 2017-12-19 23:26
Duplicate of #25

**Closed by jasarien** 2017-12-19 23:26 UTC
Labels: Duplicate
