### ISSUE TITLE
Add support for N64 Games

### ISSUE THREAD

**Issue by Marcocanc** [jasarien/Provenance#175] opened 2015-11-04 08:11 UTC
Would be awesome to be able to play N64 Games on tvOS.
[OpenEmu has a Mupen64Plus Core](https://github.com/OpenEmu/Mupen64Plus-Core).
Since the other cores are also based on OpenEmu, would it be possible to port that over?

**Comment by jasarien** [comment] 2015-11-04 08:27
Duplicate of #17. Please read through other issues before posting new ones.

**Closed by jasarien** 2015-11-04 08:27 UTC

**Comment by Cosmo** [comment] 2015-11-04 21:33
@jasarien 
is this a technical issue? is there hope?
just asking, because there's no text in #17 :)

**Comment by jasarien** [comment] 2015-11-04 21:34
It's just not planned currently. It might happen in the future but not for now.
