### ISSUE TITLE
Any update on cheat code manager?

### ISSUE THREAD

**Issue by halolordkiller3** [jasarien/Provenance#619] opened 2017-12-04 21:26 UTC
Has there been any progress towards a cheat code manager? This seems to be the only emulator that is really optimized to take advantage of the iPhone X screen.

**Comment by JoeMatt** [comment] 2017-12-17 04:53
This is something I know very little about since I never used codes in other emulators. The difficulty here is that every core uses their own cheat code system if even supported at all. Also UI would have to be implemented. I see OpenEMU, our cousin project, does implement cheat codes for limited number of cores. It's worth considering but development resources at the moment are probably better directed to better causes such as performance, importing, crashes etc. Though if anyone is willing to take this on it would be appreciated. In the mean time I'm going to close this as a duplicate of #22

**Closed by JoeMatt** 2017-12-17 04:53 UTC
