### ISSUE TITLE
Can't access menu with MFI controller plugged in

### ISSUE THREAD

**Issue by MysticalOS** [jasarien/Provenance#323] opened 2016-03-29 22:16 UTC
biggest issue I have right now is I literally have to unplug my game vice any time i want to change games or do anything in menu really. The touch buttons (including "menu") vanish when mfi is plugged in. the problem is, there isn't a single button on controller itself that can call menu function. This is using a Game Vice for iphone 6S plus. 

Ideal solution I suppose would be to hide all of touch buttons EXCEPT menu. the tiny menu button is not at all intrusive and just having it there would help immensely

**Comment by jasarien** [comment] 2016-03-29 22:41
If this is the controller you're talking about (http://www.apple.com/shop/product/HJEN2VC/A/gamevice-controller-for-iphone-6-6-plus-and-iphone-6s-6s-plus?fnode=a3) then it does have a pause button, on the right side, near the ABXY buttons. This is the menu button and it will show the menu.

This is a duplicate of #311 and it has been fixed in the latest code.

**Closed by jasarien** 2016-03-29 22:41 UTC

**Comment by MysticalOS** [comment] 2016-03-29 22:45
that button does NOT bring up the menu though. it doesn't do anything.

**Comment by starlessblack** [comment] 2017-01-04 02:07
So I just downloaded and built ver 1.3.1 a few days ago, and I'm having this problem as well. SteelSeries Nimbus controller, ATV4 running latest iOS ver.10.1--Menu button on Nimbus controller goes straight back to Provenance games library, not to in-game menu. My workaround has been to quickly double-tap the Siri button on the ATV remote which briefly brings up the Siri listening dialog but also has the side effect of pausing the game and bringing up the in-game menu.

I also noticed that if I turned on the iCade controller support in Provenance settings, it appears to fix the menu button issue, however, it also appears to map the Nimbus' "B" button to Menu. Or, rather, it's double-mapped--if you hit the B button, you can briefly see your in-game sprite or whatever start doing what it's supposed to do (jump, shoot, stab, run, flee, fly, kick, dance, etc.), but only for a brief millisecond before the in-game menu pops up.

**Comment by meldridge** [comment] 2017-03-12 05:31
Having the same issue: I have the GameVice controller GV156, and the problem is intermittent. Sometimes the controller pause button will bring up the Provenence menu, other times it does nothing.

It's an annoying bug to track down as sometimes a restart or force-quit of Provenence will fix the issue.
