### ISSUE TITLE
Improve way of browsing the game library (all > consoles > letters / genre?)

### ISSUE THREAD

**Issue by txcx** [jasarien/Provenance#448] opened 2016-10-23 16:00 UTC
Hey :)

I would really appreciate to have a kind of a better way to browse the game library. If you came over a bunch of hundred games it nearly gets impossible even to find a game. Just by doing a clear search for the exact title.

I would suggest a information architecture of 3 levels with view and filter options.
This can be integrated in a sticking top filter bar.

Top Bar could be like this:
(left: Level and View), (right: Filters)
Level, View, Filters

3 Examples for filter bar at top:
1. Home (Consoles), Gallery, Filters: Keyword, Letter
2. Game Boy, List, Filters: (none)
3. SNES (Z), Gallery, Filters: Genre

Hitting Gallery comes up with a picker to choose: Gallery or List (changes view)
Hitting Filters comes up with a search bar at top and some filter settings

Hierarchy of Browsing

Level 1 (Homescreen Consoles A-Z)
Example Console #1 
Example  Console #2 
…

Level 2 (option to switch between genre/letter)
Genre #1 (or Letter A)
Genre #2 (or Letter B)
…

Level 3 (Games A-Z)
A Game
A second Game
…

List could have some details: console, title, genre
Gallery: Like already

That would be a great improvement regarding user experience.

**Comment by jasarien** [comment] 2016-11-01 23:36
Duplicate of #3

**Closed by jasarien** 2016-11-01 23:36 UTC
