### ISSUE TITLE
Cover Art

### ISSUE THREAD

**Issue by Hanterdro** [jasarien/Provenance#237] opened 2015-12-11 08:36 UTC
Hello,

I recognized that for some SNES games the cover art is missing.
After some research  I think you guys download the coverart from a online libery via the checksum of the rom. This is not working for all Roms.

* I suggest that you offer a manuel covert art downloader, where you enter the name of the game manuel and select the cover you want.

* Or offer the the possibility to upload our own cover art for games in the GUI.

**Comment by jasarien** [comment] 2015-12-11 08:38
Duplicate of #173

**Closed by jasarien** 2015-12-11 08:38 UTC
