### ISSUE TITLE
What happened to the control pad and buttons

### ISSUE THREAD

**Issue by Neatstar** [jasarien/Provenance#587] opened 2017-08-06 18:22 UTC
I really love the provenance app. I really do. It gives me great access to games that I have grown up with and love. But it gets difficult to adjust to the way the control pads are in a fixed positioned. I thought it would be easier if you could bring back the feature that allows you to adjust and move the D Pad and buttons in any place you want on screen so it can be easier for those with a difficult reach ad finger issues

**Comment by Neatstar** [comment] 2017-08-06 18:30
I do feel like the app could benefit a lot with the option to be able to freely move the D Pad and buttons around to fit to your liking. If this feature came back, it would be really appreciated

**Comment by jasarien** [comment] 2017-12-19 23:46
Duplicate of #25

**Closed by jasarien** 2017-12-19 23:46 UTC
