### ISSUE TITLE
TVos Controller Support

### ISSUE THREAD

**Issue by Xtheman166** [jasarien/Provenance#267] opened 2016-01-05 17:16 UTC
I got Provenance onto my apple tv. It was fun until I learned that the apple tv remote was super hard to use with it. Being  a gamer I naturally have tons of controllers but none are MFI. I don't feel like spending a 50-80 bucks for a controller that I will most likely only use for Provenance. I was wondering if you could add controller support for the wii u pro controller, xbox one, or PS4 Dualshock? Any of those will work. Thanks!

**Comment by jasarien** [comment] 2016-01-05 17:19
It isn't possible to connect those kinds of controllers or use them with iOS apps without a jailbroken iOS device. Also, duplicate of #95

**Closed by jasarien** 2016-01-05 17:19 UTC
