### ISSUE TITLE
Scanlines & CRT filters

### ISSUE THREAD

**Issue by sakuranbokun** [jasarien/Provenance#251] opened 2015-12-21 08:25 UTC
I've been playing a good amount of OpenEmu lately, and it has a nice selection of filter effects. Some of which add scanlines and some very convincing CRT style blur, colour bleed, and phosphor glow effects. It looks remarkably like a real CRT.

I realise OpenEmu is running on a Mac, and so has power to burn, but would it be possible to replicate any CRT style effects in Provenance? Crisp and blocky is nice, but fuzzy, glowy, scan line covered CRT is proper old school.

**Comment by pmp174** [comment] 2015-12-21 14:02
#54  is already opened for this

**Comment by jasarien** [comment] 2015-12-21 15:26
Correct, dupe of #54

**Closed by jasarien** 2015-12-21 15:26 UTC
