### ISSUE TITLE
Cannot Save Game Battery and States SNES

### ISSUE THREAD

**Issue by G3NSVRV** [jasarien/Provenance#540] opened 2017-03-01 21:59 UTC
I cannot save game battery and game states in Kirby Super Deluxe, Hoshi no Kirby Super Star (both Roms of no-intro).

I'm using Provenance 1.3.2 (builds.io), and iOS 10.3 on iPhone 5

**Comment by lolkthxbai** [comment] 2017-03-02 02:12
Hi @G3NSVRV 

The issue your experiencing may have already been fixed. The apps hosted on websites such as, builds.io, do not always have the latest version of those apps. Currently, builds.io is hosting version 1.3.2, revision 5b7e242, which is outdated. If you want the latest version, the best way to do so is by side-loading the app via Xcode on a Mac or using Cydia Impactor on a Windows PC. Instructions for both methods can be found on the wiki page and best of all, is free.

Also note, iOS 10.3 is currently in beta and not considered "stable". Beta versions of iOS are not supported for installing Provenance through either of the methods I mentioned earlier unless you have a PAID developer account. You may get lucky and have no issues while using iOS betas but I suspect your issue is related to Apple introducing a new filesystem (APFS) and Provenance has not been updated to run properly on iOS 10.3.

Lastly, consider that what you pay to install Provenance from builds.io does not go to the developer @jasarien that worked hard to create this app.

**Comment by G3NSVRV** [comment] 2017-03-02 02:38
Thanks for all, I'll keep using builds.io<http://builds.io> because it's easy to install any app right on the phone; maybe you should create a similar platform. Also, I only have this in SNES emulation.

Regards

Sent from my iPhone

On Mar 1, 2017, at 11:12 PM, lolkthxbai <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @G3NSVRV<https://github.com/G3NSVRV>

The issue your experiencing may have already been fixed. The apps hosted on websites such as, builds.io<http://builds.io>, do not always have the latest version of those apps. Currently, builds.io<http://builds.io> is hosting version 1.3.2, revision 5b7e242<https://github.com/jasarien/Provenance/commit/5b7e24248aea1619f47d8ba082d6cf7a2ead6fa6>, which is outdated. If you want the latest version, the best way to do so is by side-loading the app via Xcode on a Mac or using Cydia Impactor on a Windows PC. Instructions for both methods can be found on the wiki page and best of all, is free.

Also note, iOS 10.3 is currently in beta and not considered "stable". Beta versions of iOS are not supported for installing Provenance through either of the methods I mentioned earlier unless you have a PAID developer account. You may get lucky and have no issues while using iOS betas but I suspect your issue is related to Apple introducing a new filesystem (APFS) and Provenance has not been updated to run properly on iOS 10.3.

Lastly, consider that what you pay to install Provenance from builds.io<http://builds.io> does not go to the developer @jasarien<https://github.com/jasarien> that worked hard to create this app.

**Comment by lolkthxbai** [comment] 2017-03-02 08:56
Hi @G3NSVRV

The platform that builds.io provides relies on registering your device with an enterprise developer account to allow you to easily install apps that can be signed by builds.io and is not subject to review by Apple. Although I can not speak for the developer I am certain that he would want as many people as possible to have access to Provenance. However, I believe that because selling UDID slots from an enterprise account is in violation of Apple's Terms of Service and may also have monetary and legal implications beyond Apple's ToS, that method of distribution is generally avoided. If you change your mind and continue having an issue after using the two methods made available through GitHub please post it here so it can be addressed
Cheers and good luck!

**Comment by G3NSVRV** [comment] 2017-03-02 14:06
You talk really funny from a guy who is offering Cydia Impactor to bypass the AppleID Account.
I will try with the version 1.3.2 27560f9 because I have time to do that now, but I'm still thinking in a similar platform (maybe free if you prefer don't have problems with Apple ToS) for users can install any emu who is offering outside of Apple Store, what is also illegal.

**Comment by jasarien** [comment] 2017-03-02 14:31
There is a huge difference between paying someone who is abusing the facilities of the apple developer program and providing an easier method for someone with a legal, valid developer account to sideload an app.

What you don't seem to understand is that using cydia Impactor to install Provenance still requires the user to have an Apple developer account (even if it's a free account). Anyone with their own developer account is free to install any application they like on their device that is registered to that developer account. 

Paying a 3rd party to sign an application for widespread public distribution is a violation of the Apple developer terms of service and will not happen here. 

They're is also the risk that the applications provided by these paid services are compromised and may include malware. The applications available at this repo will not. 

If you want to spend your money that way, that's your decision. Just know that there is a free method that doesn't violate the terms.

**Comment by jasarien** [comment] 2017-03-03 23:54
This is a duplicate of issue #193 (where you have already posted), and it seemed to be solved when the original reporter used different ROMs. I would suggest you try the same.

**Closed by jasarien** 2017-03-03 23:54 UTC
