### ISSUE TITLE
Bluetooth gamepad game frame deterioration

### ISSUE THREAD

**Issue by jamesakira** [jasarien/Provenance#660] opened 2018-01-20 18:50 UTC
Hi Jasarien,
Thank you for making this wonderful platform
I'm on the iPad Mini 2, iPhone 5, iPhone 7
Provenance version1.4 (829) release version is installed.
But the Bluetooth gaming pad 8bitdo nes30 pro, pg9023
While playing, if you try to enter a continuous button or arrow key
Game slows down and skips frames.
The game frame deterioration is happening at the time of continuous key input in the Bluetooth gamepad.
This was not happening in Mame4ios.

**Comment by jasarien** [comment] 2018-01-22 10:51
I haven’t seen any reports of this issue from other iCade controller users.  Is there any more information you can provide? Is the iCade controller’s firmware updated to the latest version?

**Comment by pabloarista** [comment] 2018-01-24 01:43
I actually just came on here looking to see if there was an issue for this. I just started using this app a few weeks ago and been using the 8bitdo rb8 n64 and the same thing happens to me. It kind of sucks if you're at a boss and you have to press the buttons fast. I did upgrade to the latest firmware and still the problem persists. I thought perhaps it was because I was too far away and the reception degrades, but even with having the control so close the problem is the same.

**Comment by jamesakira** [comment] 2018-01-25 02:55
thank you for answer~ 
I did firmware upgrade, but there is no big change.
actually i did reference to mame4ios open source
I have modified and tested the icade source part of the Provenance source.
but it has not improved about play on Bluetooth gamepad

I will upload videos and screenshots.

**Comment by sevdestruct** [comment] 2018-03-07 11:56
Can anyone report on this against the newer dev branch? 

significant performance boosts since then they might help.. but iCade is trouble with lack of real support from 8bitdo, they dropped iOS support in latest firmware, and the rollback firmware is basically a keyboard input hack.. so it is quite limited.

**Comment by pabloarista** [comment] 2018-03-12 01:47
I actually returned the iCade controller that I had. It was pretty bad. I bought the GameVice, which is MFi controller. No issues any more. It's the best route to go.

**Comment by sevdestruct** [comment] 2018-03-12 08:25
@pabloarista : GameVice for iPhone is sick, i have one on my iPhone X, highly recommend, but a little pricey though…

![gamevice-iphone-controls](https://user-images.githubusercontent.com/3118097/37272537-1fc72c8a-2594-11e8-8833-3c4974c09a47.jpg)

Since we don't have anyone to test what you were experiencing now, going to close this. -will reopen if it resurfaces

**Closed by sevdestruct** 2018-03-12 08:25 UTC
Labels: requires feedback

**Comment by pabloarista** [comment] 2018-03-12 14:20
@sevdestruct yes very slick indeed. Nice pic of it too. Actually it was @jamesakira that opened up this ticket, but I guess he can go ahead and reopen if he's still around.
