### ISSUE TITLE
ASPECT RATIO OPTION 4:3 or 16:9

### ISSUE THREAD

**Issue by ramone12781** [jasarien/Provenance#281] opened 2016-02-06 06:25 UTC
Can we please get this as an option? As much as I know you're against it just let us that want this have an option to.

Thanks!

**Comment by jasarien** [comment] 2016-02-06 09:17
Duplicate of #33

**Closed by jasarien** 2016-02-06 09:17 UTC

**Comment by ramone12781** [comment] 2016-11-01 06:46
you are an ASSHOLE

**Comment by jasarien** [comment] 2016-11-01 07:20
Lol

**Comment by ramone12781** [comment] 2016-11-01 07:23
Lol just jokin man I just wish we had the fullscreen option still lol I'm  just a bitter fan... Such an awesome emulator and this would just do it for me man.

**Comment by ramone12781** [comment] 2016-11-01 07:24
Lol just jokin man I just wish we had the fullscreen option still lol just a bitter fan...

Thanks,

Ramone

**Comment by ramone12781** [comment] 2016-11-01 07:25
Just for shits and giggles and my own curiosity is this really just tough to implement?

**Comment by jasarien** [comment] 2016-11-01 08:56
It's not like flipping a lightswitch, but it's also not like climbing Everest either.

It boils down to the fact that I think it's wrong.

Changing the aspect ratio stretches the pixels.

You end up with short, fat Mario, and rectangular pixels that look awful just for the sake of filling the screen. 

Less is more, dude, less is more.

**Comment by ramone12781** [comment] 2016-11-01 13:35
I totally understand resolution and aspect ratios I have worked for Comcast for the last 10 years I get your strong opinion on it. I get customers all the time complaining of why when they are watching a standard definition channel do they have black bars on the left and right side of the screen and I have to explain aspect ratios all day long and of course they don't get it but the tv manufacturers and Cable companies give them a choice on how they want to view their picture with zoom and aspect ratio settings. 

I have the same gripe you do in this market I hate watching a stretched SD feed on a HD tv and will keep those at a 4:3 ratio but in my retro gaming I love when the option is there. 

What amount of money could I offer you to implement the choice of a simple toggle switch for us the people the customer to play our classic childhood games in a nostalgic 1920x1080P?.... I'm sure this would make a lot of your user base happy along with bringing more aboard...

**Comment by jasarien** [comment] 2016-11-01 15:38
The second I start accepting money from people, or donations, this stops being my hobby project and suddenly I'm on commission to implement features people are paying for. That's called a job. I already have one of those.

**Comment by ramone12781** [comment] 2016-11-01 16:06
Ok fair enough then what about what the people want out of the goodness of your heart? I am a big fan of what you created here it's just an option. Would you at least consider it?

**Comment by ramone12781** [comment] 2016-11-01 16:08
Hey I appreciate at least the responses and I respect your views and opinions.

**Comment by jasarien** [comment] 2016-11-01 16:10
I haven't said I wouldn't accept the feature, that's why the original issue that this one duplicates is still tracked as open. If someone else wants to add the feature and submit a pull request, I'd be happy to review it.

**Comment by ramone12781** [comment] 2016-11-01 17:07
Just implement it and delete this thread no one will know...

**Comment by ramone12781** [comment] 2016-11-01 17:08
sorry submitted my last comment before reading your last comment.

**Comment by ramone12781** [comment] 2016-11-01 17:08
Thats great! So what issue is this feature causing?

**Comment by jasarien** [comment] 2016-11-01 17:18
Its not causing an issue. Its a duplicate of an existing issue: #33, which is ooooold.

**Comment by ramone12781** [comment] 2016-11-01 18:48
oh yeah i've seen that post.

**Comment by jasarien** [comment] 2016-11-01 19:06
I know you have. You left a comment on it one day before creating this issue, duplicating the other causing me to close it as a dupe and starting this conversation.

**Comment by ramone12781** [comment] 2016-11-01 19:17
Sorry brother didn't mean to be a pain. Just was really trying my best to talk you into it. Anyway man thanks for all you do and best of luck to you in your future endeavors and I will be looking forward to the day if it ever happens of Provenance In 16:9 1920x1080 beautiful stretched Super Mario resolution ;) I will follow you on twitter if you have an account and be looking for the announcement daily or a post on this thread or an email, etc... 🤞🏻🤞🏻
