### ISSUE TITLE
Library Interface tvOS

### ISSUE THREAD

**Issue by typkrft** [jasarien/Provenance#205] opened 2015-11-11 01:53 UTC
When scrolling through the library, in the last row of a console, pressing down will take you to the next row that a game in that column, even if it skips an entire console. I know it will at least skip one row (console). It's not anything major, but I feel like it should not have that behavior. 

```
        Pressing down here
                 |
game    game    game    game 

game    game  

game    game    game  --- Brings you here

```

**Comment by jasarien** [comment] 2015-11-11 23:19
This is something I've not had the time to look into, really. I know what the problem is, but not necessarily how to fix it.

The problem is that the Focus Engine (the abstract layer on the tvOS UI that decides what should be selected next when you swipe on the remote) chooses the next view by itself. There is no way to tell it exactly which item to select next, but you can give it hints, in the form of Focus Guides. Normally these can be added to the view, and that would be that, but the game library is a collection view, and its layout is all built in, I haven't customised it at all, so its behaviour is the default Apple-specified behaviour.

Therefore, I don't yet know how to set Focus Guides in a collection view layout without having to subclass and rewrite the entire layout myself, which I'm not going to do.

**Comment by typkrft** [comment] 2015-11-11 23:50
Interesting. I look into it more deeply once I break for semester. Hopefully I can contribute versus just finding issues! Thanks for all your hard work.

**Comment by seanbperiod** [comment] 2016-07-02 22:39
I'd like to add that there is a noticeable jump when scrolling that is kind of nauseating- each time i press down to go to the next row, the library scrolls down then jumps up a little bit. It seems that the initial downpress scrolls further than the row grid, and the grid re-aligns immediately afterwards.

**Comment by sevdestruct** [comment] 2018-03-07 06:52
Absorbing this into #714, which will resolve a lot of this, and the library gap jumping won't really be an issue anymore until ROM Collections #715 is implemented sometime after, and even the only when game library sorting #721 is implemented, and you sort by system... Soooo I'm gonna say this pretty much the interview into less than an edge case in light of all that. And close this.

**Closed by sevdestruct** 2018-03-07 06:52 UTC
Labels: Bug, User Interface
