### ISSUE TITLE
Feature Request: Folders instead of big list

### ISSUE THREAD

**Issue by emangamer** [jasarien/Provenance#635] opened 2017-12-30 16:07 UTC
I have a large game collection and have to scroll through most of my games to get to the PSX category. Maybe can we have a Folder view as the root and we click the system we want to load files from? Maybe Like how HappyChick does it? I think that would save on background resources too for people with large rom sets (iPad users/ Apple TV?)
![bfc43e5f-9650-439e-a43e-d8982a57915f](https://user-images.githubusercontent.com/32711803/34455634-4c8b825a-ed51-11e7-823e-371f6e3d4545.png)
![8a7913b7-06ef-4772-b0d5-dac249a77921](https://user-images.githubusercontent.com/32711803/34455635-4c98778a-ed51-11e7-93d5-52f7b56c7823.png)

**Comment by jasarien** [comment] 2018-01-01 02:35
Duplicate of #3

**Closed** 2018-01-01 02:36 UTC
Labels: Duplicate
